package com.glyk.heos.dal.dao;

import com.glyk.heos.dal.dao.水生相关性隐藻门;
import com.glyk.heos.dal.dao.水生相关性隐藻门Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface 水生相关性隐藻门Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    long countByExample(水生相关性隐藻门Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    int deleteByExample(水生相关性隐藻门Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    int insert(水生相关性隐藻门 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    int insertSelective(水生相关性隐藻门 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    List<水生相关性隐藻门> selectByExample(水生相关性隐藻门Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    水生相关性隐藻门 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") 水生相关性隐藻门 record, @Param("example") 水生相关性隐藻门Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") 水生相关性隐藻门 record, @Param("example") 水生相关性隐藻门Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(水生相关性隐藻门 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性隐藻门
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(水生相关性隐藻门 record);
}