package com.glyk.heos.dal.dao;

import com.glyk.heos.dal.dao.水生细密细胞密度;
import com.glyk.heos.dal.dao.水生细密细胞密度Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface 水生细密细胞密度Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    long countByExample(水生细密细胞密度Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    int deleteByExample(水生细密细胞密度Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    int insert(水生细密细胞密度 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    int insertSelective(水生细密细胞密度 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    List<水生细密细胞密度> selectByExample(水生细密细胞密度Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    水生细密细胞密度 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") 水生细密细胞密度 record, @Param("example") 水生细密细胞密度Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") 水生细密细胞密度 record, @Param("example") 水生细密细胞密度Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(水生细密细胞密度 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生细密细胞密度
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(水生细密细胞密度 record);
}