package com.glyk.heos.dal.dao;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class 水生多样性枝角类 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.编号
     *
     * @mbg.generated
     */
    private String 编号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.采样点位
     *
     * @mbg.generated
     */
    private String 采样点位;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.日期
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM",timezone = "GMT+8")
    private Date 日期;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.长额象鼻溞
     *
     * @mbg.generated
     */
    private String 长额象鼻溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.大洋洲弯尾溞
     *
     * @mbg.generated
     */
    private String 大洋洲弯尾溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.点滴尖额溞
     *
     * @mbg.generated
     */
    private String 点滴尖额溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.中型尖额溞
     *
     * @mbg.generated
     */
    private String 中型尖额溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.老年低额溞
     *
     * @mbg.generated
     */
    private String 老年低额溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.三角平直溞
     *
     * @mbg.generated
     */
    private String 三角平直溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.颈沟基合溞
     *
     * @mbg.generated
     */
    private String 颈沟基合溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.圆形盘肠溞
     *
     * @mbg.generated
     */
    private String 圆形盘肠溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.短尾秀体溞
     *
     * @mbg.generated
     */
    private String 短尾秀体溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.微型裸腹溞
     *
     * @mbg.generated
     */
    private String 微型裸腹溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.角突网纹溞
     *
     * @mbg.generated
     */
    private String 角突网纹溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.透明薄皮溞
     *
     * @mbg.generated
     */
    private String 透明薄皮溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.西方笔纹溞
     *
     * @mbg.generated
     */
    private String 西方笔纹溞;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生多样性枝角类.多刺粗毛溞
     *
     * @mbg.generated
     */
    private String 多刺粗毛溞;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.ID
     *
     * @return the value of 水生多样性枝角类.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.ID
     *
     * @param id the value for 水生多样性枝角类.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.编号
     *
     * @return the value of 水生多样性枝角类.编号
     *
     * @mbg.generated
     */
    public String get编号() {
        return 编号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.编号
     *
     * @param 编号 the value for 水生多样性枝角类.编号
     *
     * @mbg.generated
     */
    public void set编号(String 编号) {
        this.编号 = 编号 == null ? null : 编号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.采样点位
     *
     * @return the value of 水生多样性枝角类.采样点位
     *
     * @mbg.generated
     */
    public String get采样点位() {
        return 采样点位;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.采样点位
     *
     * @param 采样点位 the value for 水生多样性枝角类.采样点位
     *
     * @mbg.generated
     */
    public void set采样点位(String 采样点位) {
        this.采样点位 = 采样点位 == null ? null : 采样点位.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.日期
     *
     * @return the value of 水生多样性枝角类.日期
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM",timezone = "GMT+8")
    public Date get日期() {
        return 日期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.日期
     *
     * @param 日期 the value for 水生多样性枝角类.日期
     *
     * @mbg.generated
     */
    public void set日期(Date 日期) {
        this.日期 = 日期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.长额象鼻溞
     *
     * @return the value of 水生多样性枝角类.长额象鼻溞
     *
     * @mbg.generated
     */
    public String get长额象鼻溞() {
        return 长额象鼻溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.长额象鼻溞
     *
     * @param 长额象鼻溞 the value for 水生多样性枝角类.长额象鼻溞
     *
     * @mbg.generated
     */
    public void set长额象鼻溞(String 长额象鼻溞) {
        this.长额象鼻溞 = 长额象鼻溞 == null ? null : 长额象鼻溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.大洋洲弯尾溞
     *
     * @return the value of 水生多样性枝角类.大洋洲弯尾溞
     *
     * @mbg.generated
     */
    public String get大洋洲弯尾溞() {
        return 大洋洲弯尾溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.大洋洲弯尾溞
     *
     * @param 大洋洲弯尾溞 the value for 水生多样性枝角类.大洋洲弯尾溞
     *
     * @mbg.generated
     */
    public void set大洋洲弯尾溞(String 大洋洲弯尾溞) {
        this.大洋洲弯尾溞 = 大洋洲弯尾溞 == null ? null : 大洋洲弯尾溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.点滴尖额溞
     *
     * @return the value of 水生多样性枝角类.点滴尖额溞
     *
     * @mbg.generated
     */
    public String get点滴尖额溞() {
        return 点滴尖额溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.点滴尖额溞
     *
     * @param 点滴尖额溞 the value for 水生多样性枝角类.点滴尖额溞
     *
     * @mbg.generated
     */
    public void set点滴尖额溞(String 点滴尖额溞) {
        this.点滴尖额溞 = 点滴尖额溞 == null ? null : 点滴尖额溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.中型尖额溞
     *
     * @return the value of 水生多样性枝角类.中型尖额溞
     *
     * @mbg.generated
     */
    public String get中型尖额溞() {
        return 中型尖额溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.中型尖额溞
     *
     * @param 中型尖额溞 the value for 水生多样性枝角类.中型尖额溞
     *
     * @mbg.generated
     */
    public void set中型尖额溞(String 中型尖额溞) {
        this.中型尖额溞 = 中型尖额溞 == null ? null : 中型尖额溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.老年低额溞
     *
     * @return the value of 水生多样性枝角类.老年低额溞
     *
     * @mbg.generated
     */
    public String get老年低额溞() {
        return 老年低额溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.老年低额溞
     *
     * @param 老年低额溞 the value for 水生多样性枝角类.老年低额溞
     *
     * @mbg.generated
     */
    public void set老年低额溞(String 老年低额溞) {
        this.老年低额溞 = 老年低额溞 == null ? null : 老年低额溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.三角平直溞
     *
     * @return the value of 水生多样性枝角类.三角平直溞
     *
     * @mbg.generated
     */
    public String get三角平直溞() {
        return 三角平直溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.三角平直溞
     *
     * @param 三角平直溞 the value for 水生多样性枝角类.三角平直溞
     *
     * @mbg.generated
     */
    public void set三角平直溞(String 三角平直溞) {
        this.三角平直溞 = 三角平直溞 == null ? null : 三角平直溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.颈沟基合溞
     *
     * @return the value of 水生多样性枝角类.颈沟基合溞
     *
     * @mbg.generated
     */
    public String get颈沟基合溞() {
        return 颈沟基合溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.颈沟基合溞
     *
     * @param 颈沟基合溞 the value for 水生多样性枝角类.颈沟基合溞
     *
     * @mbg.generated
     */
    public void set颈沟基合溞(String 颈沟基合溞) {
        this.颈沟基合溞 = 颈沟基合溞 == null ? null : 颈沟基合溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.圆形盘肠溞
     *
     * @return the value of 水生多样性枝角类.圆形盘肠溞
     *
     * @mbg.generated
     */
    public String get圆形盘肠溞() {
        return 圆形盘肠溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.圆形盘肠溞
     *
     * @param 圆形盘肠溞 the value for 水生多样性枝角类.圆形盘肠溞
     *
     * @mbg.generated
     */
    public void set圆形盘肠溞(String 圆形盘肠溞) {
        this.圆形盘肠溞 = 圆形盘肠溞 == null ? null : 圆形盘肠溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.短尾秀体溞
     *
     * @return the value of 水生多样性枝角类.短尾秀体溞
     *
     * @mbg.generated
     */
    public String get短尾秀体溞() {
        return 短尾秀体溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.短尾秀体溞
     *
     * @param 短尾秀体溞 the value for 水生多样性枝角类.短尾秀体溞
     *
     * @mbg.generated
     */
    public void set短尾秀体溞(String 短尾秀体溞) {
        this.短尾秀体溞 = 短尾秀体溞 == null ? null : 短尾秀体溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.微型裸腹溞
     *
     * @return the value of 水生多样性枝角类.微型裸腹溞
     *
     * @mbg.generated
     */
    public String get微型裸腹溞() {
        return 微型裸腹溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.微型裸腹溞
     *
     * @param 微型裸腹溞 the value for 水生多样性枝角类.微型裸腹溞
     *
     * @mbg.generated
     */
    public void set微型裸腹溞(String 微型裸腹溞) {
        this.微型裸腹溞 = 微型裸腹溞 == null ? null : 微型裸腹溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.角突网纹溞
     *
     * @return the value of 水生多样性枝角类.角突网纹溞
     *
     * @mbg.generated
     */
    public String get角突网纹溞() {
        return 角突网纹溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.角突网纹溞
     *
     * @param 角突网纹溞 the value for 水生多样性枝角类.角突网纹溞
     *
     * @mbg.generated
     */
    public void set角突网纹溞(String 角突网纹溞) {
        this.角突网纹溞 = 角突网纹溞 == null ? null : 角突网纹溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.透明薄皮溞
     *
     * @return the value of 水生多样性枝角类.透明薄皮溞
     *
     * @mbg.generated
     */
    public String get透明薄皮溞() {
        return 透明薄皮溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.透明薄皮溞
     *
     * @param 透明薄皮溞 the value for 水生多样性枝角类.透明薄皮溞
     *
     * @mbg.generated
     */
    public void set透明薄皮溞(String 透明薄皮溞) {
        this.透明薄皮溞 = 透明薄皮溞 == null ? null : 透明薄皮溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.西方笔纹溞
     *
     * @return the value of 水生多样性枝角类.西方笔纹溞
     *
     * @mbg.generated
     */
    public String get西方笔纹溞() {
        return 西方笔纹溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.西方笔纹溞
     *
     * @param 西方笔纹溞 the value for 水生多样性枝角类.西方笔纹溞
     *
     * @mbg.generated
     */
    public void set西方笔纹溞(String 西方笔纹溞) {
        this.西方笔纹溞 = 西方笔纹溞 == null ? null : 西方笔纹溞.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生多样性枝角类.多刺粗毛溞
     *
     * @return the value of 水生多样性枝角类.多刺粗毛溞
     *
     * @mbg.generated
     */
    public String get多刺粗毛溞() {
        return 多刺粗毛溞;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生多样性枝角类.多刺粗毛溞
     *
     * @param 多刺粗毛溞 the value for 水生多样性枝角类.多刺粗毛溞
     *
     * @mbg.generated
     */
    public void set多刺粗毛溞(String 多刺粗毛溞) {
        this.多刺粗毛溞 = 多刺粗毛溞 == null ? null : 多刺粗毛溞.trim();
    }
}