package com.glyk.heos.dal.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class 水生多样性枝角类Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public 水生多样性枝角类Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria and编号IsNull() {
            addCriterion("编号 is null");
            return (Criteria) this;
        }

        public Criteria and编号IsNotNull() {
            addCriterion("编号 is not null");
            return (Criteria) this;
        }

        public Criteria and编号EqualTo(String value) {
            addCriterion("编号 =", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotEqualTo(String value) {
            addCriterion("编号 <>", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThan(String value) {
            addCriterion("编号 >", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThanOrEqualTo(String value) {
            addCriterion("编号 >=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThan(String value) {
            addCriterion("编号 <", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThanOrEqualTo(String value) {
            addCriterion("编号 <=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号Like(String value) {
            addCriterion("编号 like", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotLike(String value) {
            addCriterion("编号 not like", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号In(List<String> values) {
            addCriterion("编号 in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotIn(List<String> values) {
            addCriterion("编号 not in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号Between(String value1, String value2) {
            addCriterion("编号 between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotBetween(String value1, String value2) {
            addCriterion("编号 not between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNull() {
            addCriterion("采样点位 is null");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNotNull() {
            addCriterion("采样点位 is not null");
            return (Criteria) this;
        }

        public Criteria and采样点位EqualTo(String value) {
            addCriterion("采样点位 =", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotEqualTo(String value) {
            addCriterion("采样点位 <>", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThan(String value) {
            addCriterion("采样点位 >", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThanOrEqualTo(String value) {
            addCriterion("采样点位 >=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThan(String value) {
            addCriterion("采样点位 <", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThanOrEqualTo(String value) {
            addCriterion("采样点位 <=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Like(String value) {
            addCriterion("采样点位 like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotLike(String value) {
            addCriterion("采样点位 not like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位In(List<String> values) {
            addCriterion("采样点位 in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotIn(List<String> values) {
            addCriterion("采样点位 not in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Between(String value1, String value2) {
            addCriterion("采样点位 between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotBetween(String value1, String value2) {
            addCriterion("采样点位 not between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and日期IsNull() {
            addCriterion("日期 is null");
            return (Criteria) this;
        }

        public Criteria and日期IsNotNull() {
            addCriterion("日期 is not null");
            return (Criteria) this;
        }

        public Criteria and日期EqualTo(Date value) {
            addCriterionForJDBCDate("日期 =", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <>", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThan(Date value) {
            addCriterionForJDBCDate("日期 >", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 >=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThan(Date value) {
            addCriterionForJDBCDate("日期 <", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期In(List<Date> values) {
            addCriterionForJDBCDate("日期 in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotIn(List<Date> values) {
            addCriterionForJDBCDate("日期 not in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期Between(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 not between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞IsNull() {
            addCriterion("长额象鼻溞 is null");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞IsNotNull() {
            addCriterion("长额象鼻溞 is not null");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞EqualTo(String value) {
            addCriterion("长额象鼻溞 =", value, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞NotEqualTo(String value) {
            addCriterion("长额象鼻溞 <>", value, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞GreaterThan(String value) {
            addCriterion("长额象鼻溞 >", value, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞GreaterThanOrEqualTo(String value) {
            addCriterion("长额象鼻溞 >=", value, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞LessThan(String value) {
            addCriterion("长额象鼻溞 <", value, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞LessThanOrEqualTo(String value) {
            addCriterion("长额象鼻溞 <=", value, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞Like(String value) {
            addCriterion("长额象鼻溞 like", value, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞NotLike(String value) {
            addCriterion("长额象鼻溞 not like", value, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞In(List<String> values) {
            addCriterion("长额象鼻溞 in", values, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞NotIn(List<String> values) {
            addCriterion("长额象鼻溞 not in", values, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞Between(String value1, String value2) {
            addCriterion("长额象鼻溞 between", value1, value2, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and长额象鼻溞NotBetween(String value1, String value2) {
            addCriterion("长额象鼻溞 not between", value1, value2, "长额象鼻溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞IsNull() {
            addCriterion("大洋洲弯尾溞 is null");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞IsNotNull() {
            addCriterion("大洋洲弯尾溞 is not null");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞EqualTo(String value) {
            addCriterion("大洋洲弯尾溞 =", value, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞NotEqualTo(String value) {
            addCriterion("大洋洲弯尾溞 <>", value, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞GreaterThan(String value) {
            addCriterion("大洋洲弯尾溞 >", value, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞GreaterThanOrEqualTo(String value) {
            addCriterion("大洋洲弯尾溞 >=", value, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞LessThan(String value) {
            addCriterion("大洋洲弯尾溞 <", value, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞LessThanOrEqualTo(String value) {
            addCriterion("大洋洲弯尾溞 <=", value, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞Like(String value) {
            addCriterion("大洋洲弯尾溞 like", value, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞NotLike(String value) {
            addCriterion("大洋洲弯尾溞 not like", value, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞In(List<String> values) {
            addCriterion("大洋洲弯尾溞 in", values, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞NotIn(List<String> values) {
            addCriterion("大洋洲弯尾溞 not in", values, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞Between(String value1, String value2) {
            addCriterion("大洋洲弯尾溞 between", value1, value2, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and大洋洲弯尾溞NotBetween(String value1, String value2) {
            addCriterion("大洋洲弯尾溞 not between", value1, value2, "大洋洲弯尾溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞IsNull() {
            addCriterion("点滴尖额溞 is null");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞IsNotNull() {
            addCriterion("点滴尖额溞 is not null");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞EqualTo(String value) {
            addCriterion("点滴尖额溞 =", value, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞NotEqualTo(String value) {
            addCriterion("点滴尖额溞 <>", value, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞GreaterThan(String value) {
            addCriterion("点滴尖额溞 >", value, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞GreaterThanOrEqualTo(String value) {
            addCriterion("点滴尖额溞 >=", value, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞LessThan(String value) {
            addCriterion("点滴尖额溞 <", value, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞LessThanOrEqualTo(String value) {
            addCriterion("点滴尖额溞 <=", value, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞Like(String value) {
            addCriterion("点滴尖额溞 like", value, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞NotLike(String value) {
            addCriterion("点滴尖额溞 not like", value, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞In(List<String> values) {
            addCriterion("点滴尖额溞 in", values, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞NotIn(List<String> values) {
            addCriterion("点滴尖额溞 not in", values, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞Between(String value1, String value2) {
            addCriterion("点滴尖额溞 between", value1, value2, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and点滴尖额溞NotBetween(String value1, String value2) {
            addCriterion("点滴尖额溞 not between", value1, value2, "点滴尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞IsNull() {
            addCriterion("中型尖额溞 is null");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞IsNotNull() {
            addCriterion("中型尖额溞 is not null");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞EqualTo(String value) {
            addCriterion("中型尖额溞 =", value, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞NotEqualTo(String value) {
            addCriterion("中型尖额溞 <>", value, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞GreaterThan(String value) {
            addCriterion("中型尖额溞 >", value, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞GreaterThanOrEqualTo(String value) {
            addCriterion("中型尖额溞 >=", value, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞LessThan(String value) {
            addCriterion("中型尖额溞 <", value, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞LessThanOrEqualTo(String value) {
            addCriterion("中型尖额溞 <=", value, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞Like(String value) {
            addCriterion("中型尖额溞 like", value, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞NotLike(String value) {
            addCriterion("中型尖额溞 not like", value, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞In(List<String> values) {
            addCriterion("中型尖额溞 in", values, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞NotIn(List<String> values) {
            addCriterion("中型尖额溞 not in", values, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞Between(String value1, String value2) {
            addCriterion("中型尖额溞 between", value1, value2, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and中型尖额溞NotBetween(String value1, String value2) {
            addCriterion("中型尖额溞 not between", value1, value2, "中型尖额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞IsNull() {
            addCriterion("老年低额溞 is null");
            return (Criteria) this;
        }

        public Criteria and老年低额溞IsNotNull() {
            addCriterion("老年低额溞 is not null");
            return (Criteria) this;
        }

        public Criteria and老年低额溞EqualTo(String value) {
            addCriterion("老年低额溞 =", value, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞NotEqualTo(String value) {
            addCriterion("老年低额溞 <>", value, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞GreaterThan(String value) {
            addCriterion("老年低额溞 >", value, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞GreaterThanOrEqualTo(String value) {
            addCriterion("老年低额溞 >=", value, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞LessThan(String value) {
            addCriterion("老年低额溞 <", value, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞LessThanOrEqualTo(String value) {
            addCriterion("老年低额溞 <=", value, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞Like(String value) {
            addCriterion("老年低额溞 like", value, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞NotLike(String value) {
            addCriterion("老年低额溞 not like", value, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞In(List<String> values) {
            addCriterion("老年低额溞 in", values, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞NotIn(List<String> values) {
            addCriterion("老年低额溞 not in", values, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞Between(String value1, String value2) {
            addCriterion("老年低额溞 between", value1, value2, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and老年低额溞NotBetween(String value1, String value2) {
            addCriterion("老年低额溞 not between", value1, value2, "老年低额溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞IsNull() {
            addCriterion("三角平直溞 is null");
            return (Criteria) this;
        }

        public Criteria and三角平直溞IsNotNull() {
            addCriterion("三角平直溞 is not null");
            return (Criteria) this;
        }

        public Criteria and三角平直溞EqualTo(String value) {
            addCriterion("三角平直溞 =", value, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞NotEqualTo(String value) {
            addCriterion("三角平直溞 <>", value, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞GreaterThan(String value) {
            addCriterion("三角平直溞 >", value, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞GreaterThanOrEqualTo(String value) {
            addCriterion("三角平直溞 >=", value, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞LessThan(String value) {
            addCriterion("三角平直溞 <", value, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞LessThanOrEqualTo(String value) {
            addCriterion("三角平直溞 <=", value, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞Like(String value) {
            addCriterion("三角平直溞 like", value, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞NotLike(String value) {
            addCriterion("三角平直溞 not like", value, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞In(List<String> values) {
            addCriterion("三角平直溞 in", values, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞NotIn(List<String> values) {
            addCriterion("三角平直溞 not in", values, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞Between(String value1, String value2) {
            addCriterion("三角平直溞 between", value1, value2, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and三角平直溞NotBetween(String value1, String value2) {
            addCriterion("三角平直溞 not between", value1, value2, "三角平直溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞IsNull() {
            addCriterion("颈沟基合溞 is null");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞IsNotNull() {
            addCriterion("颈沟基合溞 is not null");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞EqualTo(String value) {
            addCriterion("颈沟基合溞 =", value, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞NotEqualTo(String value) {
            addCriterion("颈沟基合溞 <>", value, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞GreaterThan(String value) {
            addCriterion("颈沟基合溞 >", value, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞GreaterThanOrEqualTo(String value) {
            addCriterion("颈沟基合溞 >=", value, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞LessThan(String value) {
            addCriterion("颈沟基合溞 <", value, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞LessThanOrEqualTo(String value) {
            addCriterion("颈沟基合溞 <=", value, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞Like(String value) {
            addCriterion("颈沟基合溞 like", value, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞NotLike(String value) {
            addCriterion("颈沟基合溞 not like", value, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞In(List<String> values) {
            addCriterion("颈沟基合溞 in", values, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞NotIn(List<String> values) {
            addCriterion("颈沟基合溞 not in", values, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞Between(String value1, String value2) {
            addCriterion("颈沟基合溞 between", value1, value2, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and颈沟基合溞NotBetween(String value1, String value2) {
            addCriterion("颈沟基合溞 not between", value1, value2, "颈沟基合溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞IsNull() {
            addCriterion("圆形盘肠溞 is null");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞IsNotNull() {
            addCriterion("圆形盘肠溞 is not null");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞EqualTo(String value) {
            addCriterion("圆形盘肠溞 =", value, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞NotEqualTo(String value) {
            addCriterion("圆形盘肠溞 <>", value, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞GreaterThan(String value) {
            addCriterion("圆形盘肠溞 >", value, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞GreaterThanOrEqualTo(String value) {
            addCriterion("圆形盘肠溞 >=", value, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞LessThan(String value) {
            addCriterion("圆形盘肠溞 <", value, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞LessThanOrEqualTo(String value) {
            addCriterion("圆形盘肠溞 <=", value, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞Like(String value) {
            addCriterion("圆形盘肠溞 like", value, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞NotLike(String value) {
            addCriterion("圆形盘肠溞 not like", value, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞In(List<String> values) {
            addCriterion("圆形盘肠溞 in", values, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞NotIn(List<String> values) {
            addCriterion("圆形盘肠溞 not in", values, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞Between(String value1, String value2) {
            addCriterion("圆形盘肠溞 between", value1, value2, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and圆形盘肠溞NotBetween(String value1, String value2) {
            addCriterion("圆形盘肠溞 not between", value1, value2, "圆形盘肠溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞IsNull() {
            addCriterion("短尾秀体溞 is null");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞IsNotNull() {
            addCriterion("短尾秀体溞 is not null");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞EqualTo(String value) {
            addCriterion("短尾秀体溞 =", value, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞NotEqualTo(String value) {
            addCriterion("短尾秀体溞 <>", value, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞GreaterThan(String value) {
            addCriterion("短尾秀体溞 >", value, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞GreaterThanOrEqualTo(String value) {
            addCriterion("短尾秀体溞 >=", value, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞LessThan(String value) {
            addCriterion("短尾秀体溞 <", value, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞LessThanOrEqualTo(String value) {
            addCriterion("短尾秀体溞 <=", value, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞Like(String value) {
            addCriterion("短尾秀体溞 like", value, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞NotLike(String value) {
            addCriterion("短尾秀体溞 not like", value, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞In(List<String> values) {
            addCriterion("短尾秀体溞 in", values, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞NotIn(List<String> values) {
            addCriterion("短尾秀体溞 not in", values, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞Between(String value1, String value2) {
            addCriterion("短尾秀体溞 between", value1, value2, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and短尾秀体溞NotBetween(String value1, String value2) {
            addCriterion("短尾秀体溞 not between", value1, value2, "短尾秀体溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞IsNull() {
            addCriterion("微型裸腹溞 is null");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞IsNotNull() {
            addCriterion("微型裸腹溞 is not null");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞EqualTo(String value) {
            addCriterion("微型裸腹溞 =", value, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞NotEqualTo(String value) {
            addCriterion("微型裸腹溞 <>", value, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞GreaterThan(String value) {
            addCriterion("微型裸腹溞 >", value, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞GreaterThanOrEqualTo(String value) {
            addCriterion("微型裸腹溞 >=", value, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞LessThan(String value) {
            addCriterion("微型裸腹溞 <", value, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞LessThanOrEqualTo(String value) {
            addCriterion("微型裸腹溞 <=", value, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞Like(String value) {
            addCriterion("微型裸腹溞 like", value, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞NotLike(String value) {
            addCriterion("微型裸腹溞 not like", value, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞In(List<String> values) {
            addCriterion("微型裸腹溞 in", values, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞NotIn(List<String> values) {
            addCriterion("微型裸腹溞 not in", values, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞Between(String value1, String value2) {
            addCriterion("微型裸腹溞 between", value1, value2, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and微型裸腹溞NotBetween(String value1, String value2) {
            addCriterion("微型裸腹溞 not between", value1, value2, "微型裸腹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞IsNull() {
            addCriterion("角突网纹溞 is null");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞IsNotNull() {
            addCriterion("角突网纹溞 is not null");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞EqualTo(String value) {
            addCriterion("角突网纹溞 =", value, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞NotEqualTo(String value) {
            addCriterion("角突网纹溞 <>", value, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞GreaterThan(String value) {
            addCriterion("角突网纹溞 >", value, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞GreaterThanOrEqualTo(String value) {
            addCriterion("角突网纹溞 >=", value, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞LessThan(String value) {
            addCriterion("角突网纹溞 <", value, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞LessThanOrEqualTo(String value) {
            addCriterion("角突网纹溞 <=", value, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞Like(String value) {
            addCriterion("角突网纹溞 like", value, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞NotLike(String value) {
            addCriterion("角突网纹溞 not like", value, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞In(List<String> values) {
            addCriterion("角突网纹溞 in", values, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞NotIn(List<String> values) {
            addCriterion("角突网纹溞 not in", values, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞Between(String value1, String value2) {
            addCriterion("角突网纹溞 between", value1, value2, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and角突网纹溞NotBetween(String value1, String value2) {
            addCriterion("角突网纹溞 not between", value1, value2, "角突网纹溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞IsNull() {
            addCriterion("透明薄皮溞 is null");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞IsNotNull() {
            addCriterion("透明薄皮溞 is not null");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞EqualTo(String value) {
            addCriterion("透明薄皮溞 =", value, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞NotEqualTo(String value) {
            addCriterion("透明薄皮溞 <>", value, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞GreaterThan(String value) {
            addCriterion("透明薄皮溞 >", value, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞GreaterThanOrEqualTo(String value) {
            addCriterion("透明薄皮溞 >=", value, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞LessThan(String value) {
            addCriterion("透明薄皮溞 <", value, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞LessThanOrEqualTo(String value) {
            addCriterion("透明薄皮溞 <=", value, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞Like(String value) {
            addCriterion("透明薄皮溞 like", value, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞NotLike(String value) {
            addCriterion("透明薄皮溞 not like", value, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞In(List<String> values) {
            addCriterion("透明薄皮溞 in", values, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞NotIn(List<String> values) {
            addCriterion("透明薄皮溞 not in", values, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞Between(String value1, String value2) {
            addCriterion("透明薄皮溞 between", value1, value2, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and透明薄皮溞NotBetween(String value1, String value2) {
            addCriterion("透明薄皮溞 not between", value1, value2, "透明薄皮溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞IsNull() {
            addCriterion("西方笔纹溞 is null");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞IsNotNull() {
            addCriterion("西方笔纹溞 is not null");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞EqualTo(String value) {
            addCriterion("西方笔纹溞 =", value, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞NotEqualTo(String value) {
            addCriterion("西方笔纹溞 <>", value, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞GreaterThan(String value) {
            addCriterion("西方笔纹溞 >", value, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞GreaterThanOrEqualTo(String value) {
            addCriterion("西方笔纹溞 >=", value, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞LessThan(String value) {
            addCriterion("西方笔纹溞 <", value, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞LessThanOrEqualTo(String value) {
            addCriterion("西方笔纹溞 <=", value, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞Like(String value) {
            addCriterion("西方笔纹溞 like", value, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞NotLike(String value) {
            addCriterion("西方笔纹溞 not like", value, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞In(List<String> values) {
            addCriterion("西方笔纹溞 in", values, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞NotIn(List<String> values) {
            addCriterion("西方笔纹溞 not in", values, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞Between(String value1, String value2) {
            addCriterion("西方笔纹溞 between", value1, value2, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and西方笔纹溞NotBetween(String value1, String value2) {
            addCriterion("西方笔纹溞 not between", value1, value2, "西方笔纹溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞IsNull() {
            addCriterion("多刺粗毛溞 is null");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞IsNotNull() {
            addCriterion("多刺粗毛溞 is not null");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞EqualTo(String value) {
            addCriterion("多刺粗毛溞 =", value, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞NotEqualTo(String value) {
            addCriterion("多刺粗毛溞 <>", value, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞GreaterThan(String value) {
            addCriterion("多刺粗毛溞 >", value, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞GreaterThanOrEqualTo(String value) {
            addCriterion("多刺粗毛溞 >=", value, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞LessThan(String value) {
            addCriterion("多刺粗毛溞 <", value, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞LessThanOrEqualTo(String value) {
            addCriterion("多刺粗毛溞 <=", value, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞Like(String value) {
            addCriterion("多刺粗毛溞 like", value, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞NotLike(String value) {
            addCriterion("多刺粗毛溞 not like", value, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞In(List<String> values) {
            addCriterion("多刺粗毛溞 in", values, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞NotIn(List<String> values) {
            addCriterion("多刺粗毛溞 not in", values, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞Between(String value1, String value2) {
            addCriterion("多刺粗毛溞 between", value1, value2, "多刺粗毛溞");
            return (Criteria) this;
        }

        public Criteria and多刺粗毛溞NotBetween(String value1, String value2) {
            addCriterion("多刺粗毛溞 not between", value1, value2, "多刺粗毛溞");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生多样性枝角类
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}