package com.glyk.heos.dal.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class 水生密度轮虫Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public 水生密度轮虫Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria and编号IsNull() {
            addCriterion("编号 is null");
            return (Criteria) this;
        }

        public Criteria and编号IsNotNull() {
            addCriterion("编号 is not null");
            return (Criteria) this;
        }

        public Criteria and编号EqualTo(Integer value) {
            addCriterion("编号 =", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotEqualTo(Integer value) {
            addCriterion("编号 <>", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThan(Integer value) {
            addCriterion("编号 >", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThanOrEqualTo(Integer value) {
            addCriterion("编号 >=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThan(Integer value) {
            addCriterion("编号 <", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThanOrEqualTo(Integer value) {
            addCriterion("编号 <=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号In(List<Integer> values) {
            addCriterion("编号 in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotIn(List<Integer> values) {
            addCriterion("编号 not in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号Between(Integer value1, Integer value2) {
            addCriterion("编号 between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotBetween(Integer value1, Integer value2) {
            addCriterion("编号 not between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNull() {
            addCriterion("采样点位 is null");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNotNull() {
            addCriterion("采样点位 is not null");
            return (Criteria) this;
        }

        public Criteria and采样点位EqualTo(String value) {
            addCriterion("采样点位 =", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotEqualTo(String value) {
            addCriterion("采样点位 <>", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThan(String value) {
            addCriterion("采样点位 >", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThanOrEqualTo(String value) {
            addCriterion("采样点位 >=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThan(String value) {
            addCriterion("采样点位 <", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThanOrEqualTo(String value) {
            addCriterion("采样点位 <=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Like(String value) {
            addCriterion("采样点位 like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotLike(String value) {
            addCriterion("采样点位 not like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位In(List<String> values) {
            addCriterion("采样点位 in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotIn(List<String> values) {
            addCriterion("采样点位 not in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Between(String value1, String value2) {
            addCriterion("采样点位 between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotBetween(String value1, String value2) {
            addCriterion("采样点位 not between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and日期IsNull() {
            addCriterion("日期 is null");
            return (Criteria) this;
        }

        public Criteria and日期IsNotNull() {
            addCriterion("日期 is not null");
            return (Criteria) this;
        }

        public Criteria and日期EqualTo(Date value) {
            addCriterionForJDBCDate("日期 =", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <>", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThan(Date value) {
            addCriterionForJDBCDate("日期 >", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 >=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThan(Date value) {
            addCriterionForJDBCDate("日期 <", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期In(List<Date> values) {
            addCriterionForJDBCDate("日期 in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotIn(List<Date> values) {
            addCriterionForJDBCDate("日期 not in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期Between(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 not between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫IsNull() {
            addCriterion("聚花轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫IsNotNull() {
            addCriterion("聚花轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫EqualTo(String value) {
            addCriterion("聚花轮虫 =", value, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫NotEqualTo(String value) {
            addCriterion("聚花轮虫 <>", value, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫GreaterThan(String value) {
            addCriterion("聚花轮虫 >", value, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("聚花轮虫 >=", value, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫LessThan(String value) {
            addCriterion("聚花轮虫 <", value, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫LessThanOrEqualTo(String value) {
            addCriterion("聚花轮虫 <=", value, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫Like(String value) {
            addCriterion("聚花轮虫 like", value, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫NotLike(String value) {
            addCriterion("聚花轮虫 not like", value, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫In(List<String> values) {
            addCriterion("聚花轮虫 in", values, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫NotIn(List<String> values) {
            addCriterion("聚花轮虫 not in", values, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫Between(String value1, String value2) {
            addCriterion("聚花轮虫 between", value1, value2, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and聚花轮虫NotBetween(String value1, String value2) {
            addCriterion("聚花轮虫 not between", value1, value2, "聚花轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫IsNull() {
            addCriterion("高跷轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫IsNotNull() {
            addCriterion("高跷轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫EqualTo(String value) {
            addCriterion("高跷轮虫 =", value, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫NotEqualTo(String value) {
            addCriterion("高跷轮虫 <>", value, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫GreaterThan(String value) {
            addCriterion("高跷轮虫 >", value, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("高跷轮虫 >=", value, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫LessThan(String value) {
            addCriterion("高跷轮虫 <", value, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫LessThanOrEqualTo(String value) {
            addCriterion("高跷轮虫 <=", value, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫Like(String value) {
            addCriterion("高跷轮虫 like", value, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫NotLike(String value) {
            addCriterion("高跷轮虫 not like", value, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫In(List<String> values) {
            addCriterion("高跷轮虫 in", values, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫NotIn(List<String> values) {
            addCriterion("高跷轮虫 not in", values, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫Between(String value1, String value2) {
            addCriterion("高跷轮虫 between", value1, value2, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and高跷轮虫NotBetween(String value1, String value2) {
            addCriterion("高跷轮虫 not between", value1, value2, "高跷轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫IsNull() {
            addCriterion("扁平泡轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫IsNotNull() {
            addCriterion("扁平泡轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫EqualTo(String value) {
            addCriterion("扁平泡轮虫 =", value, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫NotEqualTo(String value) {
            addCriterion("扁平泡轮虫 <>", value, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫GreaterThan(String value) {
            addCriterion("扁平泡轮虫 >", value, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("扁平泡轮虫 >=", value, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫LessThan(String value) {
            addCriterion("扁平泡轮虫 <", value, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫LessThanOrEqualTo(String value) {
            addCriterion("扁平泡轮虫 <=", value, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫Like(String value) {
            addCriterion("扁平泡轮虫 like", value, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫NotLike(String value) {
            addCriterion("扁平泡轮虫 not like", value, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫In(List<String> values) {
            addCriterion("扁平泡轮虫 in", values, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫NotIn(List<String> values) {
            addCriterion("扁平泡轮虫 not in", values, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫Between(String value1, String value2) {
            addCriterion("扁平泡轮虫 between", value1, value2, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and扁平泡轮虫NotBetween(String value1, String value2) {
            addCriterion("扁平泡轮虫 not between", value1, value2, "扁平泡轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫IsNull() {
            addCriterion("月形腔轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫IsNotNull() {
            addCriterion("月形腔轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫EqualTo(String value) {
            addCriterion("月形腔轮虫 =", value, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫NotEqualTo(String value) {
            addCriterion("月形腔轮虫 <>", value, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫GreaterThan(String value) {
            addCriterion("月形腔轮虫 >", value, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("月形腔轮虫 >=", value, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫LessThan(String value) {
            addCriterion("月形腔轮虫 <", value, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫LessThanOrEqualTo(String value) {
            addCriterion("月形腔轮虫 <=", value, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫Like(String value) {
            addCriterion("月形腔轮虫 like", value, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫NotLike(String value) {
            addCriterion("月形腔轮虫 not like", value, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫In(List<String> values) {
            addCriterion("月形腔轮虫 in", values, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫NotIn(List<String> values) {
            addCriterion("月形腔轮虫 not in", values, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫Between(String value1, String value2) {
            addCriterion("月形腔轮虫 between", value1, value2, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and月形腔轮虫NotBetween(String value1, String value2) {
            addCriterion("月形腔轮虫 not between", value1, value2, "月形腔轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫IsNull() {
            addCriterion("广布多肢轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫IsNotNull() {
            addCriterion("广布多肢轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫EqualTo(String value) {
            addCriterion("广布多肢轮虫 =", value, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫NotEqualTo(String value) {
            addCriterion("广布多肢轮虫 <>", value, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫GreaterThan(String value) {
            addCriterion("广布多肢轮虫 >", value, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("广布多肢轮虫 >=", value, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫LessThan(String value) {
            addCriterion("广布多肢轮虫 <", value, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫LessThanOrEqualTo(String value) {
            addCriterion("广布多肢轮虫 <=", value, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫Like(String value) {
            addCriterion("广布多肢轮虫 like", value, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫NotLike(String value) {
            addCriterion("广布多肢轮虫 not like", value, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫In(List<String> values) {
            addCriterion("广布多肢轮虫 in", values, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫NotIn(List<String> values) {
            addCriterion("广布多肢轮虫 not in", values, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫Between(String value1, String value2) {
            addCriterion("广布多肢轮虫 between", value1, value2, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and广布多肢轮虫NotBetween(String value1, String value2) {
            addCriterion("广布多肢轮虫 not between", value1, value2, "广布多肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫IsNull() {
            addCriterion("迈氏三肢轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫IsNotNull() {
            addCriterion("迈氏三肢轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫EqualTo(String value) {
            addCriterion("迈氏三肢轮虫 =", value, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫NotEqualTo(String value) {
            addCriterion("迈氏三肢轮虫 <>", value, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫GreaterThan(String value) {
            addCriterion("迈氏三肢轮虫 >", value, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("迈氏三肢轮虫 >=", value, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫LessThan(String value) {
            addCriterion("迈氏三肢轮虫 <", value, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫LessThanOrEqualTo(String value) {
            addCriterion("迈氏三肢轮虫 <=", value, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫Like(String value) {
            addCriterion("迈氏三肢轮虫 like", value, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫NotLike(String value) {
            addCriterion("迈氏三肢轮虫 not like", value, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫In(List<String> values) {
            addCriterion("迈氏三肢轮虫 in", values, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫NotIn(List<String> values) {
            addCriterion("迈氏三肢轮虫 not in", values, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫Between(String value1, String value2) {
            addCriterion("迈氏三肢轮虫 between", value1, value2, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and迈氏三肢轮虫NotBetween(String value1, String value2) {
            addCriterion("迈氏三肢轮虫 not between", value1, value2, "迈氏三肢轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫IsNull() {
            addCriterion("螺形龟甲轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫IsNotNull() {
            addCriterion("螺形龟甲轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫EqualTo(String value) {
            addCriterion("螺形龟甲轮虫 =", value, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫NotEqualTo(String value) {
            addCriterion("螺形龟甲轮虫 <>", value, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫GreaterThan(String value) {
            addCriterion("螺形龟甲轮虫 >", value, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("螺形龟甲轮虫 >=", value, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫LessThan(String value) {
            addCriterion("螺形龟甲轮虫 <", value, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫LessThanOrEqualTo(String value) {
            addCriterion("螺形龟甲轮虫 <=", value, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫Like(String value) {
            addCriterion("螺形龟甲轮虫 like", value, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫NotLike(String value) {
            addCriterion("螺形龟甲轮虫 not like", value, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫In(List<String> values) {
            addCriterion("螺形龟甲轮虫 in", values, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫NotIn(List<String> values) {
            addCriterion("螺形龟甲轮虫 not in", values, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫Between(String value1, String value2) {
            addCriterion("螺形龟甲轮虫 between", value1, value2, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and螺形龟甲轮虫NotBetween(String value1, String value2) {
            addCriterion("螺形龟甲轮虫 not between", value1, value2, "螺形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫IsNull() {
            addCriterion("曲腿龟甲轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫IsNotNull() {
            addCriterion("曲腿龟甲轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫EqualTo(String value) {
            addCriterion("曲腿龟甲轮虫 =", value, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫NotEqualTo(String value) {
            addCriterion("曲腿龟甲轮虫 <>", value, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫GreaterThan(String value) {
            addCriterion("曲腿龟甲轮虫 >", value, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("曲腿龟甲轮虫 >=", value, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫LessThan(String value) {
            addCriterion("曲腿龟甲轮虫 <", value, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫LessThanOrEqualTo(String value) {
            addCriterion("曲腿龟甲轮虫 <=", value, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫Like(String value) {
            addCriterion("曲腿龟甲轮虫 like", value, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫NotLike(String value) {
            addCriterion("曲腿龟甲轮虫 not like", value, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫In(List<String> values) {
            addCriterion("曲腿龟甲轮虫 in", values, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫NotIn(List<String> values) {
            addCriterion("曲腿龟甲轮虫 not in", values, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫Between(String value1, String value2) {
            addCriterion("曲腿龟甲轮虫 between", value1, value2, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and曲腿龟甲轮虫NotBetween(String value1, String value2) {
            addCriterion("曲腿龟甲轮虫 not between", value1, value2, "曲腿龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫IsNull() {
            addCriterion("矩形龟甲轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫IsNotNull() {
            addCriterion("矩形龟甲轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫EqualTo(String value) {
            addCriterion("矩形龟甲轮虫 =", value, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫NotEqualTo(String value) {
            addCriterion("矩形龟甲轮虫 <>", value, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫GreaterThan(String value) {
            addCriterion("矩形龟甲轮虫 >", value, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("矩形龟甲轮虫 >=", value, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫LessThan(String value) {
            addCriterion("矩形龟甲轮虫 <", value, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫LessThanOrEqualTo(String value) {
            addCriterion("矩形龟甲轮虫 <=", value, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫Like(String value) {
            addCriterion("矩形龟甲轮虫 like", value, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫NotLike(String value) {
            addCriterion("矩形龟甲轮虫 not like", value, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫In(List<String> values) {
            addCriterion("矩形龟甲轮虫 in", values, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫NotIn(List<String> values) {
            addCriterion("矩形龟甲轮虫 not in", values, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫Between(String value1, String value2) {
            addCriterion("矩形龟甲轮虫 between", value1, value2, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and矩形龟甲轮虫NotBetween(String value1, String value2) {
            addCriterion("矩形龟甲轮虫 not between", value1, value2, "矩形龟甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫IsNull() {
            addCriterion("爱德里亚狭甲轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫IsNotNull() {
            addCriterion("爱德里亚狭甲轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫EqualTo(String value) {
            addCriterion("爱德里亚狭甲轮虫 =", value, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫NotEqualTo(String value) {
            addCriterion("爱德里亚狭甲轮虫 <>", value, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫GreaterThan(String value) {
            addCriterion("爱德里亚狭甲轮虫 >", value, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("爱德里亚狭甲轮虫 >=", value, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫LessThan(String value) {
            addCriterion("爱德里亚狭甲轮虫 <", value, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫LessThanOrEqualTo(String value) {
            addCriterion("爱德里亚狭甲轮虫 <=", value, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫Like(String value) {
            addCriterion("爱德里亚狭甲轮虫 like", value, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫NotLike(String value) {
            addCriterion("爱德里亚狭甲轮虫 not like", value, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫In(List<String> values) {
            addCriterion("爱德里亚狭甲轮虫 in", values, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫NotIn(List<String> values) {
            addCriterion("爱德里亚狭甲轮虫 not in", values, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫Between(String value1, String value2) {
            addCriterion("爱德里亚狭甲轮虫 between", value1, value2, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and爱德里亚狭甲轮虫NotBetween(String value1, String value2) {
            addCriterion("爱德里亚狭甲轮虫 not between", value1, value2, "爱德里亚狭甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫IsNull() {
            addCriterion("盘状鞍甲轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫IsNotNull() {
            addCriterion("盘状鞍甲轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫EqualTo(String value) {
            addCriterion("盘状鞍甲轮虫 =", value, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫NotEqualTo(String value) {
            addCriterion("盘状鞍甲轮虫 <>", value, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫GreaterThan(String value) {
            addCriterion("盘状鞍甲轮虫 >", value, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("盘状鞍甲轮虫 >=", value, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫LessThan(String value) {
            addCriterion("盘状鞍甲轮虫 <", value, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫LessThanOrEqualTo(String value) {
            addCriterion("盘状鞍甲轮虫 <=", value, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫Like(String value) {
            addCriterion("盘状鞍甲轮虫 like", value, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫NotLike(String value) {
            addCriterion("盘状鞍甲轮虫 not like", value, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫In(List<String> values) {
            addCriterion("盘状鞍甲轮虫 in", values, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫NotIn(List<String> values) {
            addCriterion("盘状鞍甲轮虫 not in", values, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫Between(String value1, String value2) {
            addCriterion("盘状鞍甲轮虫 between", value1, value2, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and盘状鞍甲轮虫NotBetween(String value1, String value2) {
            addCriterion("盘状鞍甲轮虫 not between", value1, value2, "盘状鞍甲轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫IsNull() {
            addCriterion("前节晶囊轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫IsNotNull() {
            addCriterion("前节晶囊轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫EqualTo(String value) {
            addCriterion("前节晶囊轮虫 =", value, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫NotEqualTo(String value) {
            addCriterion("前节晶囊轮虫 <>", value, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫GreaterThan(String value) {
            addCriterion("前节晶囊轮虫 >", value, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("前节晶囊轮虫 >=", value, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫LessThan(String value) {
            addCriterion("前节晶囊轮虫 <", value, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫LessThanOrEqualTo(String value) {
            addCriterion("前节晶囊轮虫 <=", value, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫Like(String value) {
            addCriterion("前节晶囊轮虫 like", value, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫NotLike(String value) {
            addCriterion("前节晶囊轮虫 not like", value, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫In(List<String> values) {
            addCriterion("前节晶囊轮虫 in", values, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫NotIn(List<String> values) {
            addCriterion("前节晶囊轮虫 not in", values, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫Between(String value1, String value2) {
            addCriterion("前节晶囊轮虫 between", value1, value2, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and前节晶囊轮虫NotBetween(String value1, String value2) {
            addCriterion("前节晶囊轮虫 not between", value1, value2, "前节晶囊轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫IsNull() {
            addCriterion("萼花臂尾轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫IsNotNull() {
            addCriterion("萼花臂尾轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫EqualTo(String value) {
            addCriterion("萼花臂尾轮虫 =", value, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫NotEqualTo(String value) {
            addCriterion("萼花臂尾轮虫 <>", value, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫GreaterThan(String value) {
            addCriterion("萼花臂尾轮虫 >", value, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("萼花臂尾轮虫 >=", value, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫LessThan(String value) {
            addCriterion("萼花臂尾轮虫 <", value, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫LessThanOrEqualTo(String value) {
            addCriterion("萼花臂尾轮虫 <=", value, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫Like(String value) {
            addCriterion("萼花臂尾轮虫 like", value, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫NotLike(String value) {
            addCriterion("萼花臂尾轮虫 not like", value, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫In(List<String> values) {
            addCriterion("萼花臂尾轮虫 in", values, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫NotIn(List<String> values) {
            addCriterion("萼花臂尾轮虫 not in", values, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫Between(String value1, String value2) {
            addCriterion("萼花臂尾轮虫 between", value1, value2, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and萼花臂尾轮虫NotBetween(String value1, String value2) {
            addCriterion("萼花臂尾轮虫 not between", value1, value2, "萼花臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫IsNull() {
            addCriterion("等刺异尾轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫IsNotNull() {
            addCriterion("等刺异尾轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫EqualTo(String value) {
            addCriterion("等刺异尾轮虫 =", value, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫NotEqualTo(String value) {
            addCriterion("等刺异尾轮虫 <>", value, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫GreaterThan(String value) {
            addCriterion("等刺异尾轮虫 >", value, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("等刺异尾轮虫 >=", value, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫LessThan(String value) {
            addCriterion("等刺异尾轮虫 <", value, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫LessThanOrEqualTo(String value) {
            addCriterion("等刺异尾轮虫 <=", value, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫Like(String value) {
            addCriterion("等刺异尾轮虫 like", value, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫NotLike(String value) {
            addCriterion("等刺异尾轮虫 not like", value, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫In(List<String> values) {
            addCriterion("等刺异尾轮虫 in", values, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫NotIn(List<String> values) {
            addCriterion("等刺异尾轮虫 not in", values, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫Between(String value1, String value2) {
            addCriterion("等刺异尾轮虫 between", value1, value2, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and等刺异尾轮虫NotBetween(String value1, String value2) {
            addCriterion("等刺异尾轮虫 not between", value1, value2, "等刺异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫IsNull() {
            addCriterion("刺盖异尾轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫IsNotNull() {
            addCriterion("刺盖异尾轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫EqualTo(String value) {
            addCriterion("刺盖异尾轮虫 =", value, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫NotEqualTo(String value) {
            addCriterion("刺盖异尾轮虫 <>", value, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫GreaterThan(String value) {
            addCriterion("刺盖异尾轮虫 >", value, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("刺盖异尾轮虫 >=", value, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫LessThan(String value) {
            addCriterion("刺盖异尾轮虫 <", value, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫LessThanOrEqualTo(String value) {
            addCriterion("刺盖异尾轮虫 <=", value, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫Like(String value) {
            addCriterion("刺盖异尾轮虫 like", value, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫NotLike(String value) {
            addCriterion("刺盖异尾轮虫 not like", value, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫In(List<String> values) {
            addCriterion("刺盖异尾轮虫 in", values, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫NotIn(List<String> values) {
            addCriterion("刺盖异尾轮虫 not in", values, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫Between(String value1, String value2) {
            addCriterion("刺盖异尾轮虫 between", value1, value2, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and刺盖异尾轮虫NotBetween(String value1, String value2) {
            addCriterion("刺盖异尾轮虫 not between", value1, value2, "刺盖异尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫IsNull() {
            addCriterion("纤巧同尾轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫IsNotNull() {
            addCriterion("纤巧同尾轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫EqualTo(String value) {
            addCriterion("纤巧同尾轮虫 =", value, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫NotEqualTo(String value) {
            addCriterion("纤巧同尾轮虫 <>", value, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫GreaterThan(String value) {
            addCriterion("纤巧同尾轮虫 >", value, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("纤巧同尾轮虫 >=", value, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫LessThan(String value) {
            addCriterion("纤巧同尾轮虫 <", value, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫LessThanOrEqualTo(String value) {
            addCriterion("纤巧同尾轮虫 <=", value, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫Like(String value) {
            addCriterion("纤巧同尾轮虫 like", value, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫NotLike(String value) {
            addCriterion("纤巧同尾轮虫 not like", value, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫In(List<String> values) {
            addCriterion("纤巧同尾轮虫 in", values, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫NotIn(List<String> values) {
            addCriterion("纤巧同尾轮虫 not in", values, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫Between(String value1, String value2) {
            addCriterion("纤巧同尾轮虫 between", value1, value2, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and纤巧同尾轮虫NotBetween(String value1, String value2) {
            addCriterion("纤巧同尾轮虫 not between", value1, value2, "纤巧同尾轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫IsNull() {
            addCriterion("腹棘管轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫IsNotNull() {
            addCriterion("腹棘管轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫EqualTo(String value) {
            addCriterion("腹棘管轮虫 =", value, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫NotEqualTo(String value) {
            addCriterion("腹棘管轮虫 <>", value, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫GreaterThan(String value) {
            addCriterion("腹棘管轮虫 >", value, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("腹棘管轮虫 >=", value, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫LessThan(String value) {
            addCriterion("腹棘管轮虫 <", value, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫LessThanOrEqualTo(String value) {
            addCriterion("腹棘管轮虫 <=", value, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫Like(String value) {
            addCriterion("腹棘管轮虫 like", value, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫NotLike(String value) {
            addCriterion("腹棘管轮虫 not like", value, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫In(List<String> values) {
            addCriterion("腹棘管轮虫 in", values, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫NotIn(List<String> values) {
            addCriterion("腹棘管轮虫 not in", values, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫Between(String value1, String value2) {
            addCriterion("腹棘管轮虫 between", value1, value2, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and腹棘管轮虫NotBetween(String value1, String value2) {
            addCriterion("腹棘管轮虫 not between", value1, value2, "腹棘管轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫IsNull() {
            addCriterion("梨形单趾轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫IsNotNull() {
            addCriterion("梨形单趾轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫EqualTo(String value) {
            addCriterion("梨形单趾轮虫 =", value, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫NotEqualTo(String value) {
            addCriterion("梨形单趾轮虫 <>", value, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫GreaterThan(String value) {
            addCriterion("梨形单趾轮虫 >", value, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("梨形单趾轮虫 >=", value, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫LessThan(String value) {
            addCriterion("梨形单趾轮虫 <", value, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫LessThanOrEqualTo(String value) {
            addCriterion("梨形单趾轮虫 <=", value, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫Like(String value) {
            addCriterion("梨形单趾轮虫 like", value, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫NotLike(String value) {
            addCriterion("梨形单趾轮虫 not like", value, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫In(List<String> values) {
            addCriterion("梨形单趾轮虫 in", values, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫NotIn(List<String> values) {
            addCriterion("梨形单趾轮虫 not in", values, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫Between(String value1, String value2) {
            addCriterion("梨形单趾轮虫 between", value1, value2, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and梨形单趾轮虫NotBetween(String value1, String value2) {
            addCriterion("梨形单趾轮虫 not between", value1, value2, "梨形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫IsNull() {
            addCriterion("囊形单趾轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫IsNotNull() {
            addCriterion("囊形单趾轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫EqualTo(String value) {
            addCriterion("囊形单趾轮虫 =", value, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫NotEqualTo(String value) {
            addCriterion("囊形单趾轮虫 <>", value, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫GreaterThan(String value) {
            addCriterion("囊形单趾轮虫 >", value, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("囊形单趾轮虫 >=", value, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫LessThan(String value) {
            addCriterion("囊形单趾轮虫 <", value, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫LessThanOrEqualTo(String value) {
            addCriterion("囊形单趾轮虫 <=", value, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫Like(String value) {
            addCriterion("囊形单趾轮虫 like", value, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫NotLike(String value) {
            addCriterion("囊形单趾轮虫 not like", value, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫In(List<String> values) {
            addCriterion("囊形单趾轮虫 in", values, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫NotIn(List<String> values) {
            addCriterion("囊形单趾轮虫 not in", values, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫Between(String value1, String value2) {
            addCriterion("囊形单趾轮虫 between", value1, value2, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and囊形单趾轮虫NotBetween(String value1, String value2) {
            addCriterion("囊形单趾轮虫 not between", value1, value2, "囊形单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫IsNull() {
            addCriterion("尖趾单趾轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫IsNotNull() {
            addCriterion("尖趾单趾轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫EqualTo(String value) {
            addCriterion("尖趾单趾轮虫 =", value, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫NotEqualTo(String value) {
            addCriterion("尖趾单趾轮虫 <>", value, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫GreaterThan(String value) {
            addCriterion("尖趾单趾轮虫 >", value, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("尖趾单趾轮虫 >=", value, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫LessThan(String value) {
            addCriterion("尖趾单趾轮虫 <", value, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫LessThanOrEqualTo(String value) {
            addCriterion("尖趾单趾轮虫 <=", value, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫Like(String value) {
            addCriterion("尖趾单趾轮虫 like", value, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫NotLike(String value) {
            addCriterion("尖趾单趾轮虫 not like", value, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫In(List<String> values) {
            addCriterion("尖趾单趾轮虫 in", values, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫NotIn(List<String> values) {
            addCriterion("尖趾单趾轮虫 not in", values, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫Between(String value1, String value2) {
            addCriterion("尖趾单趾轮虫 between", value1, value2, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and尖趾单趾轮虫NotBetween(String value1, String value2) {
            addCriterion("尖趾单趾轮虫 not between", value1, value2, "尖趾单趾轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫IsNull() {
            addCriterion("大肚须足轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫IsNotNull() {
            addCriterion("大肚须足轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫EqualTo(String value) {
            addCriterion("大肚须足轮虫 =", value, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫NotEqualTo(String value) {
            addCriterion("大肚须足轮虫 <>", value, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫GreaterThan(String value) {
            addCriterion("大肚须足轮虫 >", value, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("大肚须足轮虫 >=", value, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫LessThan(String value) {
            addCriterion("大肚须足轮虫 <", value, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫LessThanOrEqualTo(String value) {
            addCriterion("大肚须足轮虫 <=", value, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫Like(String value) {
            addCriterion("大肚须足轮虫 like", value, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫NotLike(String value) {
            addCriterion("大肚须足轮虫 not like", value, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫In(List<String> values) {
            addCriterion("大肚须足轮虫 in", values, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫NotIn(List<String> values) {
            addCriterion("大肚须足轮虫 not in", values, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫Between(String value1, String value2) {
            addCriterion("大肚须足轮虫 between", value1, value2, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and大肚须足轮虫NotBetween(String value1, String value2) {
            addCriterion("大肚须足轮虫 not between", value1, value2, "大肚须足轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫IsNull() {
            addCriterion("裂痕龟纹轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫IsNotNull() {
            addCriterion("裂痕龟纹轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫EqualTo(String value) {
            addCriterion("裂痕龟纹轮虫 =", value, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫NotEqualTo(String value) {
            addCriterion("裂痕龟纹轮虫 <>", value, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫GreaterThan(String value) {
            addCriterion("裂痕龟纹轮虫 >", value, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("裂痕龟纹轮虫 >=", value, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫LessThan(String value) {
            addCriterion("裂痕龟纹轮虫 <", value, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫LessThanOrEqualTo(String value) {
            addCriterion("裂痕龟纹轮虫 <=", value, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫Like(String value) {
            addCriterion("裂痕龟纹轮虫 like", value, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫NotLike(String value) {
            addCriterion("裂痕龟纹轮虫 not like", value, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫In(List<String> values) {
            addCriterion("裂痕龟纹轮虫 in", values, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫NotIn(List<String> values) {
            addCriterion("裂痕龟纹轮虫 not in", values, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫Between(String value1, String value2) {
            addCriterion("裂痕龟纹轮虫 between", value1, value2, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and裂痕龟纹轮虫NotBetween(String value1, String value2) {
            addCriterion("裂痕龟纹轮虫 not between", value1, value2, "裂痕龟纹轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫IsNull() {
            addCriterion("疣毛轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫IsNotNull() {
            addCriterion("疣毛轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫EqualTo(String value) {
            addCriterion("疣毛轮虫 =", value, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫NotEqualTo(String value) {
            addCriterion("疣毛轮虫 <>", value, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫GreaterThan(String value) {
            addCriterion("疣毛轮虫 >", value, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("疣毛轮虫 >=", value, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫LessThan(String value) {
            addCriterion("疣毛轮虫 <", value, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫LessThanOrEqualTo(String value) {
            addCriterion("疣毛轮虫 <=", value, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫Like(String value) {
            addCriterion("疣毛轮虫 like", value, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫NotLike(String value) {
            addCriterion("疣毛轮虫 not like", value, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫In(List<String> values) {
            addCriterion("疣毛轮虫 in", values, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫NotIn(List<String> values) {
            addCriterion("疣毛轮虫 not in", values, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫Between(String value1, String value2) {
            addCriterion("疣毛轮虫 between", value1, value2, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and疣毛轮虫NotBetween(String value1, String value2) {
            addCriterion("疣毛轮虫 not between", value1, value2, "疣毛轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫IsNull() {
            addCriterion("多态胶鞘轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫IsNotNull() {
            addCriterion("多态胶鞘轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫EqualTo(String value) {
            addCriterion("多态胶鞘轮虫 =", value, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫NotEqualTo(String value) {
            addCriterion("多态胶鞘轮虫 <>", value, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫GreaterThan(String value) {
            addCriterion("多态胶鞘轮虫 >", value, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("多态胶鞘轮虫 >=", value, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫LessThan(String value) {
            addCriterion("多态胶鞘轮虫 <", value, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫LessThanOrEqualTo(String value) {
            addCriterion("多态胶鞘轮虫 <=", value, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫Like(String value) {
            addCriterion("多态胶鞘轮虫 like", value, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫NotLike(String value) {
            addCriterion("多态胶鞘轮虫 not like", value, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫In(List<String> values) {
            addCriterion("多态胶鞘轮虫 in", values, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫NotIn(List<String> values) {
            addCriterion("多态胶鞘轮虫 not in", values, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫Between(String value1, String value2) {
            addCriterion("多态胶鞘轮虫 between", value1, value2, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and多态胶鞘轮虫NotBetween(String value1, String value2) {
            addCriterion("多态胶鞘轮虫 not between", value1, value2, "多态胶鞘轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫IsNull() {
            addCriterion("角突臂尾轮虫 is null");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫IsNotNull() {
            addCriterion("角突臂尾轮虫 is not null");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫EqualTo(String value) {
            addCriterion("角突臂尾轮虫 =", value, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫NotEqualTo(String value) {
            addCriterion("角突臂尾轮虫 <>", value, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫GreaterThan(String value) {
            addCriterion("角突臂尾轮虫 >", value, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫GreaterThanOrEqualTo(String value) {
            addCriterion("角突臂尾轮虫 >=", value, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫LessThan(String value) {
            addCriterion("角突臂尾轮虫 <", value, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫LessThanOrEqualTo(String value) {
            addCriterion("角突臂尾轮虫 <=", value, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫Like(String value) {
            addCriterion("角突臂尾轮虫 like", value, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫NotLike(String value) {
            addCriterion("角突臂尾轮虫 not like", value, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫In(List<String> values) {
            addCriterion("角突臂尾轮虫 in", values, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫NotIn(List<String> values) {
            addCriterion("角突臂尾轮虫 not in", values, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫Between(String value1, String value2) {
            addCriterion("角突臂尾轮虫 between", value1, value2, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and角突臂尾轮虫NotBetween(String value1, String value2) {
            addCriterion("角突臂尾轮虫 not between", value1, value2, "角突臂尾轮虫");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种IsNull() {
            addCriterion("轮虫未定种 is null");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种IsNotNull() {
            addCriterion("轮虫未定种 is not null");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种EqualTo(String value) {
            addCriterion("轮虫未定种 =", value, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种NotEqualTo(String value) {
            addCriterion("轮虫未定种 <>", value, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种GreaterThan(String value) {
            addCriterion("轮虫未定种 >", value, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种GreaterThanOrEqualTo(String value) {
            addCriterion("轮虫未定种 >=", value, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种LessThan(String value) {
            addCriterion("轮虫未定种 <", value, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种LessThanOrEqualTo(String value) {
            addCriterion("轮虫未定种 <=", value, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种Like(String value) {
            addCriterion("轮虫未定种 like", value, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种NotLike(String value) {
            addCriterion("轮虫未定种 not like", value, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种In(List<String> values) {
            addCriterion("轮虫未定种 in", values, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种NotIn(List<String> values) {
            addCriterion("轮虫未定种 not in", values, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种Between(String value1, String value2) {
            addCriterion("轮虫未定种 between", value1, value2, "轮虫未定种");
            return (Criteria) this;
        }

        public Criteria and轮虫未定种NotBetween(String value1, String value2) {
            addCriterion("轮虫未定种 not between", value1, value2, "轮虫未定种");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生密度轮虫
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}