package com.glyk.heos.dal.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class 水生相关性蓝藻门Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public 水生相关性蓝藻门Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria and编号IsNull() {
            addCriterion("编号 is null");
            return (Criteria) this;
        }

        public Criteria and编号IsNotNull() {
            addCriterion("编号 is not null");
            return (Criteria) this;
        }

        public Criteria and编号EqualTo(String value) {
            addCriterion("编号 =", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotEqualTo(String value) {
            addCriterion("编号 <>", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThan(String value) {
            addCriterion("编号 >", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThanOrEqualTo(String value) {
            addCriterion("编号 >=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThan(String value) {
            addCriterion("编号 <", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThanOrEqualTo(String value) {
            addCriterion("编号 <=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号Like(String value) {
            addCriterion("编号 like", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotLike(String value) {
            addCriterion("编号 not like", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号In(List<String> values) {
            addCriterion("编号 in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotIn(List<String> values) {
            addCriterion("编号 not in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号Between(String value1, String value2) {
            addCriterion("编号 between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotBetween(String value1, String value2) {
            addCriterion("编号 not between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNull() {
            addCriterion("采样点位 is null");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNotNull() {
            addCriterion("采样点位 is not null");
            return (Criteria) this;
        }

        public Criteria and采样点位EqualTo(String value) {
            addCriterion("采样点位 =", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotEqualTo(String value) {
            addCriterion("采样点位 <>", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThan(String value) {
            addCriterion("采样点位 >", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThanOrEqualTo(String value) {
            addCriterion("采样点位 >=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThan(String value) {
            addCriterion("采样点位 <", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThanOrEqualTo(String value) {
            addCriterion("采样点位 <=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Like(String value) {
            addCriterion("采样点位 like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotLike(String value) {
            addCriterion("采样点位 not like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位In(List<String> values) {
            addCriterion("采样点位 in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotIn(List<String> values) {
            addCriterion("采样点位 not in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Between(String value1, String value2) {
            addCriterion("采样点位 between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotBetween(String value1, String value2) {
            addCriterion("采样点位 not between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and日期IsNull() {
            addCriterion("日期 is null");
            return (Criteria) this;
        }

        public Criteria and日期IsNotNull() {
            addCriterion("日期 is not null");
            return (Criteria) this;
        }

        public Criteria and日期EqualTo(Date value) {
            addCriterionForJDBCDate("日期 =", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <>", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThan(Date value) {
            addCriterionForJDBCDate("日期 >", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 >=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThan(Date value) {
            addCriterionForJDBCDate("日期 <", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期In(List<Date> values) {
            addCriterionForJDBCDate("日期 in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotIn(List<Date> values) {
            addCriterionForJDBCDate("日期 not in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期Between(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 not between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻IsNull() {
            addCriterion("铜绿微囊藻 is null");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻IsNotNull() {
            addCriterion("铜绿微囊藻 is not null");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻EqualTo(String value) {
            addCriterion("铜绿微囊藻 =", value, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻NotEqualTo(String value) {
            addCriterion("铜绿微囊藻 <>", value, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻GreaterThan(String value) {
            addCriterion("铜绿微囊藻 >", value, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻GreaterThanOrEqualTo(String value) {
            addCriterion("铜绿微囊藻 >=", value, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻LessThan(String value) {
            addCriterion("铜绿微囊藻 <", value, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻LessThanOrEqualTo(String value) {
            addCriterion("铜绿微囊藻 <=", value, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻Like(String value) {
            addCriterion("铜绿微囊藻 like", value, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻NotLike(String value) {
            addCriterion("铜绿微囊藻 not like", value, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻In(List<String> values) {
            addCriterion("铜绿微囊藻 in", values, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻NotIn(List<String> values) {
            addCriterion("铜绿微囊藻 not in", values, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻Between(String value1, String value2) {
            addCriterion("铜绿微囊藻 between", value1, value2, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and铜绿微囊藻NotBetween(String value1, String value2) {
            addCriterion("铜绿微囊藻 not between", value1, value2, "铜绿微囊藻");
            return (Criteria) this;
        }

        public Criteria and色球藻IsNull() {
            addCriterion("色球藻 is null");
            return (Criteria) this;
        }

        public Criteria and色球藻IsNotNull() {
            addCriterion("色球藻 is not null");
            return (Criteria) this;
        }

        public Criteria and色球藻EqualTo(String value) {
            addCriterion("色球藻 =", value, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻NotEqualTo(String value) {
            addCriterion("色球藻 <>", value, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻GreaterThan(String value) {
            addCriterion("色球藻 >", value, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻GreaterThanOrEqualTo(String value) {
            addCriterion("色球藻 >=", value, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻LessThan(String value) {
            addCriterion("色球藻 <", value, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻LessThanOrEqualTo(String value) {
            addCriterion("色球藻 <=", value, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻Like(String value) {
            addCriterion("色球藻 like", value, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻NotLike(String value) {
            addCriterion("色球藻 not like", value, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻In(List<String> values) {
            addCriterion("色球藻 in", values, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻NotIn(List<String> values) {
            addCriterion("色球藻 not in", values, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻Between(String value1, String value2) {
            addCriterion("色球藻 between", value1, value2, "色球藻");
            return (Criteria) this;
        }

        public Criteria and色球藻NotBetween(String value1, String value2) {
            addCriterion("色球藻 not between", value1, value2, "色球藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻IsNull() {
            addCriterion("假鱼腥藻 is null");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻IsNotNull() {
            addCriterion("假鱼腥藻 is not null");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻EqualTo(String value) {
            addCriterion("假鱼腥藻 =", value, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻NotEqualTo(String value) {
            addCriterion("假鱼腥藻 <>", value, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻GreaterThan(String value) {
            addCriterion("假鱼腥藻 >", value, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻GreaterThanOrEqualTo(String value) {
            addCriterion("假鱼腥藻 >=", value, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻LessThan(String value) {
            addCriterion("假鱼腥藻 <", value, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻LessThanOrEqualTo(String value) {
            addCriterion("假鱼腥藻 <=", value, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻Like(String value) {
            addCriterion("假鱼腥藻 like", value, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻NotLike(String value) {
            addCriterion("假鱼腥藻 not like", value, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻In(List<String> values) {
            addCriterion("假鱼腥藻 in", values, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻NotIn(List<String> values) {
            addCriterion("假鱼腥藻 not in", values, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻Between(String value1, String value2) {
            addCriterion("假鱼腥藻 between", value1, value2, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and假鱼腥藻NotBetween(String value1, String value2) {
            addCriterion("假鱼腥藻 not between", value1, value2, "假鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻IsNull() {
            addCriterion("水华鱼腥藻 is null");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻IsNotNull() {
            addCriterion("水华鱼腥藻 is not null");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻EqualTo(String value) {
            addCriterion("水华鱼腥藻 =", value, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻NotEqualTo(String value) {
            addCriterion("水华鱼腥藻 <>", value, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻GreaterThan(String value) {
            addCriterion("水华鱼腥藻 >", value, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻GreaterThanOrEqualTo(String value) {
            addCriterion("水华鱼腥藻 >=", value, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻LessThan(String value) {
            addCriterion("水华鱼腥藻 <", value, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻LessThanOrEqualTo(String value) {
            addCriterion("水华鱼腥藻 <=", value, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻Like(String value) {
            addCriterion("水华鱼腥藻 like", value, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻NotLike(String value) {
            addCriterion("水华鱼腥藻 not like", value, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻In(List<String> values) {
            addCriterion("水华鱼腥藻 in", values, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻NotIn(List<String> values) {
            addCriterion("水华鱼腥藻 not in", values, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻Between(String value1, String value2) {
            addCriterion("水华鱼腥藻 between", value1, value2, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and水华鱼腥藻NotBetween(String value1, String value2) {
            addCriterion("水华鱼腥藻 not between", value1, value2, "水华鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻IsNull() {
            addCriterion("鱼腥藻 is null");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻IsNotNull() {
            addCriterion("鱼腥藻 is not null");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻EqualTo(String value) {
            addCriterion("鱼腥藻 =", value, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻NotEqualTo(String value) {
            addCriterion("鱼腥藻 <>", value, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻GreaterThan(String value) {
            addCriterion("鱼腥藻 >", value, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻GreaterThanOrEqualTo(String value) {
            addCriterion("鱼腥藻 >=", value, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻LessThan(String value) {
            addCriterion("鱼腥藻 <", value, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻LessThanOrEqualTo(String value) {
            addCriterion("鱼腥藻 <=", value, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻Like(String value) {
            addCriterion("鱼腥藻 like", value, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻NotLike(String value) {
            addCriterion("鱼腥藻 not like", value, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻In(List<String> values) {
            addCriterion("鱼腥藻 in", values, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻NotIn(List<String> values) {
            addCriterion("鱼腥藻 not in", values, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻Between(String value1, String value2) {
            addCriterion("鱼腥藻 between", value1, value2, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and鱼腥藻NotBetween(String value1, String value2) {
            addCriterion("鱼腥藻 not between", value1, value2, "鱼腥藻");
            return (Criteria) this;
        }

        public Criteria and小席藻IsNull() {
            addCriterion("小席藻 is null");
            return (Criteria) this;
        }

        public Criteria and小席藻IsNotNull() {
            addCriterion("小席藻 is not null");
            return (Criteria) this;
        }

        public Criteria and小席藻EqualTo(String value) {
            addCriterion("小席藻 =", value, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻NotEqualTo(String value) {
            addCriterion("小席藻 <>", value, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻GreaterThan(String value) {
            addCriterion("小席藻 >", value, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻GreaterThanOrEqualTo(String value) {
            addCriterion("小席藻 >=", value, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻LessThan(String value) {
            addCriterion("小席藻 <", value, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻LessThanOrEqualTo(String value) {
            addCriterion("小席藻 <=", value, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻Like(String value) {
            addCriterion("小席藻 like", value, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻NotLike(String value) {
            addCriterion("小席藻 not like", value, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻In(List<String> values) {
            addCriterion("小席藻 in", values, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻NotIn(List<String> values) {
            addCriterion("小席藻 not in", values, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻Between(String value1, String value2) {
            addCriterion("小席藻 between", value1, value2, "小席藻");
            return (Criteria) this;
        }

        public Criteria and小席藻NotBetween(String value1, String value2) {
            addCriterion("小席藻 not between", value1, value2, "小席藻");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生相关性蓝藻门
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}