package com.glyk.heos.dal.dao;

public class 水生密度浮游动物 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生密度浮游动物.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生密度浮游动物.类型
     *
     * @mbg.generated
     */
    private String 类型;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生密度浮游动物.中文名
     *
     * @mbg.generated
     */
    private String 中文名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 水生密度浮游动物.拉丁名
     *
     * @mbg.generated
     */
    private String 拉丁名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生密度浮游动物.ID
     *
     * @return the value of 水生密度浮游动物.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生密度浮游动物.ID
     *
     * @param id the value for 水生密度浮游动物.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生密度浮游动物.类型
     *
     * @return the value of 水生密度浮游动物.类型
     *
     * @mbg.generated
     */
    public String get类型() {
        return 类型;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生密度浮游动物.类型
     *
     * @param 类型 the value for 水生密度浮游动物.类型
     *
     * @mbg.generated
     */
    public void set类型(String 类型) {
        this.类型 = 类型 == null ? null : 类型.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生密度浮游动物.中文名
     *
     * @return the value of 水生密度浮游动物.中文名
     *
     * @mbg.generated
     */
    public String get中文名() {
        return 中文名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生密度浮游动物.中文名
     *
     * @param 中文名 the value for 水生密度浮游动物.中文名
     *
     * @mbg.generated
     */
    public void set中文名(String 中文名) {
        this.中文名 = 中文名 == null ? null : 中文名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 水生密度浮游动物.拉丁名
     *
     * @return the value of 水生密度浮游动物.拉丁名
     *
     * @mbg.generated
     */
    public String get拉丁名() {
        return 拉丁名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 水生密度浮游动物.拉丁名
     *
     * @param 拉丁名 the value for 水生密度浮游动物.拉丁名
     *
     * @mbg.generated
     */
    public void set拉丁名(String 拉丁名) {
        this.拉丁名 = 拉丁名 == null ? null : 拉丁名.trim();
    }
}