package com.glyk.heos.dal.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class 水生多样性足类Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public 水生多样性足类Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria and编号IsNull() {
            addCriterion("编号 is null");
            return (Criteria) this;
        }

        public Criteria and编号IsNotNull() {
            addCriterion("编号 is not null");
            return (Criteria) this;
        }

        public Criteria and编号EqualTo(String value) {
            addCriterion("编号 =", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotEqualTo(String value) {
            addCriterion("编号 <>", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThan(String value) {
            addCriterion("编号 >", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThanOrEqualTo(String value) {
            addCriterion("编号 >=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThan(String value) {
            addCriterion("编号 <", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThanOrEqualTo(String value) {
            addCriterion("编号 <=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号Like(String value) {
            addCriterion("编号 like", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotLike(String value) {
            addCriterion("编号 not like", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号In(List<String> values) {
            addCriterion("编号 in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotIn(List<String> values) {
            addCriterion("编号 not in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号Between(String value1, String value2) {
            addCriterion("编号 between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotBetween(String value1, String value2) {
            addCriterion("编号 not between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNull() {
            addCriterion("采样点位 is null");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNotNull() {
            addCriterion("采样点位 is not null");
            return (Criteria) this;
        }

        public Criteria and采样点位EqualTo(String value) {
            addCriterion("采样点位 =", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotEqualTo(String value) {
            addCriterion("采样点位 <>", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThan(String value) {
            addCriterion("采样点位 >", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThanOrEqualTo(String value) {
            addCriterion("采样点位 >=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThan(String value) {
            addCriterion("采样点位 <", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThanOrEqualTo(String value) {
            addCriterion("采样点位 <=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Like(String value) {
            addCriterion("采样点位 like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotLike(String value) {
            addCriterion("采样点位 not like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位In(List<String> values) {
            addCriterion("采样点位 in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotIn(List<String> values) {
            addCriterion("采样点位 not in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Between(String value1, String value2) {
            addCriterion("采样点位 between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotBetween(String value1, String value2) {
            addCriterion("采样点位 not between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and日期IsNull() {
            addCriterion("日期 is null");
            return (Criteria) this;
        }

        public Criteria and日期IsNotNull() {
            addCriterion("日期 is not null");
            return (Criteria) this;
        }

        public Criteria and日期EqualTo(Date value) {
            addCriterionForJDBCDate("日期 =", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <>", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThan(Date value) {
            addCriterionForJDBCDate("日期 >", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 >=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThan(Date value) {
            addCriterionForJDBCDate("日期 <", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期In(List<Date> values) {
            addCriterionForJDBCDate("日期 in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotIn(List<Date> values) {
            addCriterionForJDBCDate("日期 not in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期Between(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 not between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤IsNull() {
            addCriterion("汤匙华哲水蚤 is null");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤IsNotNull() {
            addCriterion("汤匙华哲水蚤 is not null");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤EqualTo(String value) {
            addCriterion("汤匙华哲水蚤 =", value, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤NotEqualTo(String value) {
            addCriterion("汤匙华哲水蚤 <>", value, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤GreaterThan(String value) {
            addCriterion("汤匙华哲水蚤 >", value, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤GreaterThanOrEqualTo(String value) {
            addCriterion("汤匙华哲水蚤 >=", value, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤LessThan(String value) {
            addCriterion("汤匙华哲水蚤 <", value, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤LessThanOrEqualTo(String value) {
            addCriterion("汤匙华哲水蚤 <=", value, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤Like(String value) {
            addCriterion("汤匙华哲水蚤 like", value, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤NotLike(String value) {
            addCriterion("汤匙华哲水蚤 not like", value, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤In(List<String> values) {
            addCriterion("汤匙华哲水蚤 in", values, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤NotIn(List<String> values) {
            addCriterion("汤匙华哲水蚤 not in", values, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤Between(String value1, String value2) {
            addCriterion("汤匙华哲水蚤 between", value1, value2, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and汤匙华哲水蚤NotBetween(String value1, String value2) {
            addCriterion("汤匙华哲水蚤 not between", value1, value2, "汤匙华哲水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤IsNull() {
            addCriterion("中华窄腹水蚤 is null");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤IsNotNull() {
            addCriterion("中华窄腹水蚤 is not null");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤EqualTo(String value) {
            addCriterion("中华窄腹水蚤 =", value, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤NotEqualTo(String value) {
            addCriterion("中华窄腹水蚤 <>", value, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤GreaterThan(String value) {
            addCriterion("中华窄腹水蚤 >", value, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤GreaterThanOrEqualTo(String value) {
            addCriterion("中华窄腹水蚤 >=", value, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤LessThan(String value) {
            addCriterion("中华窄腹水蚤 <", value, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤LessThanOrEqualTo(String value) {
            addCriterion("中华窄腹水蚤 <=", value, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤Like(String value) {
            addCriterion("中华窄腹水蚤 like", value, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤NotLike(String value) {
            addCriterion("中华窄腹水蚤 not like", value, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤In(List<String> values) {
            addCriterion("中华窄腹水蚤 in", values, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤NotIn(List<String> values) {
            addCriterion("中华窄腹水蚤 not in", values, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤Between(String value1, String value2) {
            addCriterion("中华窄腹水蚤 between", value1, value2, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and中华窄腹水蚤NotBetween(String value1, String value2) {
            addCriterion("中华窄腹水蚤 not between", value1, value2, "中华窄腹水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤IsNull() {
            addCriterion("跨立小剑水蚤 is null");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤IsNotNull() {
            addCriterion("跨立小剑水蚤 is not null");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤EqualTo(String value) {
            addCriterion("跨立小剑水蚤 =", value, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤NotEqualTo(String value) {
            addCriterion("跨立小剑水蚤 <>", value, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤GreaterThan(String value) {
            addCriterion("跨立小剑水蚤 >", value, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤GreaterThanOrEqualTo(String value) {
            addCriterion("跨立小剑水蚤 >=", value, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤LessThan(String value) {
            addCriterion("跨立小剑水蚤 <", value, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤LessThanOrEqualTo(String value) {
            addCriterion("跨立小剑水蚤 <=", value, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤Like(String value) {
            addCriterion("跨立小剑水蚤 like", value, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤NotLike(String value) {
            addCriterion("跨立小剑水蚤 not like", value, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤In(List<String> values) {
            addCriterion("跨立小剑水蚤 in", values, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤NotIn(List<String> values) {
            addCriterion("跨立小剑水蚤 not in", values, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤Between(String value1, String value2) {
            addCriterion("跨立小剑水蚤 between", value1, value2, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and跨立小剑水蚤NotBetween(String value1, String value2) {
            addCriterion("跨立小剑水蚤 not between", value1, value2, "跨立小剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤IsNull() {
            addCriterion("广布中剑水蚤 is null");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤IsNotNull() {
            addCriterion("广布中剑水蚤 is not null");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤EqualTo(String value) {
            addCriterion("广布中剑水蚤 =", value, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤NotEqualTo(String value) {
            addCriterion("广布中剑水蚤 <>", value, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤GreaterThan(String value) {
            addCriterion("广布中剑水蚤 >", value, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤GreaterThanOrEqualTo(String value) {
            addCriterion("广布中剑水蚤 >=", value, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤LessThan(String value) {
            addCriterion("广布中剑水蚤 <", value, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤LessThanOrEqualTo(String value) {
            addCriterion("广布中剑水蚤 <=", value, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤Like(String value) {
            addCriterion("广布中剑水蚤 like", value, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤NotLike(String value) {
            addCriterion("广布中剑水蚤 not like", value, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤In(List<String> values) {
            addCriterion("广布中剑水蚤 in", values, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤NotIn(List<String> values) {
            addCriterion("广布中剑水蚤 not in", values, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤Between(String value1, String value2) {
            addCriterion("广布中剑水蚤 between", value1, value2, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and广布中剑水蚤NotBetween(String value1, String value2) {
            addCriterion("广布中剑水蚤 not between", value1, value2, "广布中剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤IsNull() {
            addCriterion("台湾温剑水蚤 is null");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤IsNotNull() {
            addCriterion("台湾温剑水蚤 is not null");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤EqualTo(String value) {
            addCriterion("台湾温剑水蚤 =", value, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤NotEqualTo(String value) {
            addCriterion("台湾温剑水蚤 <>", value, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤GreaterThan(String value) {
            addCriterion("台湾温剑水蚤 >", value, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤GreaterThanOrEqualTo(String value) {
            addCriterion("台湾温剑水蚤 >=", value, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤LessThan(String value) {
            addCriterion("台湾温剑水蚤 <", value, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤LessThanOrEqualTo(String value) {
            addCriterion("台湾温剑水蚤 <=", value, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤Like(String value) {
            addCriterion("台湾温剑水蚤 like", value, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤NotLike(String value) {
            addCriterion("台湾温剑水蚤 not like", value, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤In(List<String> values) {
            addCriterion("台湾温剑水蚤 in", values, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤NotIn(List<String> values) {
            addCriterion("台湾温剑水蚤 not in", values, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤Between(String value1, String value2) {
            addCriterion("台湾温剑水蚤 between", value1, value2, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and台湾温剑水蚤NotBetween(String value1, String value2) {
            addCriterion("台湾温剑水蚤 not between", value1, value2, "台湾温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤IsNull() {
            addCriterion("球状许水蚤 is null");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤IsNotNull() {
            addCriterion("球状许水蚤 is not null");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤EqualTo(String value) {
            addCriterion("球状许水蚤 =", value, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤NotEqualTo(String value) {
            addCriterion("球状许水蚤 <>", value, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤GreaterThan(String value) {
            addCriterion("球状许水蚤 >", value, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤GreaterThanOrEqualTo(String value) {
            addCriterion("球状许水蚤 >=", value, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤LessThan(String value) {
            addCriterion("球状许水蚤 <", value, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤LessThanOrEqualTo(String value) {
            addCriterion("球状许水蚤 <=", value, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤Like(String value) {
            addCriterion("球状许水蚤 like", value, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤NotLike(String value) {
            addCriterion("球状许水蚤 not like", value, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤In(List<String> values) {
            addCriterion("球状许水蚤 in", values, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤NotIn(List<String> values) {
            addCriterion("球状许水蚤 not in", values, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤Between(String value1, String value2) {
            addCriterion("球状许水蚤 between", value1, value2, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and球状许水蚤NotBetween(String value1, String value2) {
            addCriterion("球状许水蚤 not between", value1, value2, "球状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤IsNull() {
            addCriterion("指状许水蚤 is null");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤IsNotNull() {
            addCriterion("指状许水蚤 is not null");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤EqualTo(String value) {
            addCriterion("指状许水蚤 =", value, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤NotEqualTo(String value) {
            addCriterion("指状许水蚤 <>", value, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤GreaterThan(String value) {
            addCriterion("指状许水蚤 >", value, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤GreaterThanOrEqualTo(String value) {
            addCriterion("指状许水蚤 >=", value, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤LessThan(String value) {
            addCriterion("指状许水蚤 <", value, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤LessThanOrEqualTo(String value) {
            addCriterion("指状许水蚤 <=", value, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤Like(String value) {
            addCriterion("指状许水蚤 like", value, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤NotLike(String value) {
            addCriterion("指状许水蚤 not like", value, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤In(List<String> values) {
            addCriterion("指状许水蚤 in", values, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤NotIn(List<String> values) {
            addCriterion("指状许水蚤 not in", values, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤Between(String value1, String value2) {
            addCriterion("指状许水蚤 between", value1, value2, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and指状许水蚤NotBetween(String value1, String value2) {
            addCriterion("指状许水蚤 not between", value1, value2, "指状许水蚤");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体IsNull() {
            addCriterion("剑水蚤桡足幼体 is null");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体IsNotNull() {
            addCriterion("剑水蚤桡足幼体 is not null");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体EqualTo(String value) {
            addCriterion("剑水蚤桡足幼体 =", value, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体NotEqualTo(String value) {
            addCriterion("剑水蚤桡足幼体 <>", value, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体GreaterThan(String value) {
            addCriterion("剑水蚤桡足幼体 >", value, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体GreaterThanOrEqualTo(String value) {
            addCriterion("剑水蚤桡足幼体 >=", value, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体LessThan(String value) {
            addCriterion("剑水蚤桡足幼体 <", value, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体LessThanOrEqualTo(String value) {
            addCriterion("剑水蚤桡足幼体 <=", value, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体Like(String value) {
            addCriterion("剑水蚤桡足幼体 like", value, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体NotLike(String value) {
            addCriterion("剑水蚤桡足幼体 not like", value, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体In(List<String> values) {
            addCriterion("剑水蚤桡足幼体 in", values, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体NotIn(List<String> values) {
            addCriterion("剑水蚤桡足幼体 not in", values, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体Between(String value1, String value2) {
            addCriterion("剑水蚤桡足幼体 between", value1, value2, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and剑水蚤桡足幼体NotBetween(String value1, String value2) {
            addCriterion("剑水蚤桡足幼体 not between", value1, value2, "剑水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体IsNull() {
            addCriterion("哲水蚤桡足幼体 is null");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体IsNotNull() {
            addCriterion("哲水蚤桡足幼体 is not null");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体EqualTo(String value) {
            addCriterion("哲水蚤桡足幼体 =", value, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体NotEqualTo(String value) {
            addCriterion("哲水蚤桡足幼体 <>", value, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体GreaterThan(String value) {
            addCriterion("哲水蚤桡足幼体 >", value, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体GreaterThanOrEqualTo(String value) {
            addCriterion("哲水蚤桡足幼体 >=", value, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体LessThan(String value) {
            addCriterion("哲水蚤桡足幼体 <", value, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体LessThanOrEqualTo(String value) {
            addCriterion("哲水蚤桡足幼体 <=", value, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体Like(String value) {
            addCriterion("哲水蚤桡足幼体 like", value, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体NotLike(String value) {
            addCriterion("哲水蚤桡足幼体 not like", value, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体In(List<String> values) {
            addCriterion("哲水蚤桡足幼体 in", values, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体NotIn(List<String> values) {
            addCriterion("哲水蚤桡足幼体 not in", values, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体Between(String value1, String value2) {
            addCriterion("哲水蚤桡足幼体 between", value1, value2, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and哲水蚤桡足幼体NotBetween(String value1, String value2) {
            addCriterion("哲水蚤桡足幼体 not between", value1, value2, "哲水蚤桡足幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体IsNull() {
            addCriterion("无节幼体 is null");
            return (Criteria) this;
        }

        public Criteria and无节幼体IsNotNull() {
            addCriterion("无节幼体 is not null");
            return (Criteria) this;
        }

        public Criteria and无节幼体EqualTo(String value) {
            addCriterion("无节幼体 =", value, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体NotEqualTo(String value) {
            addCriterion("无节幼体 <>", value, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体GreaterThan(String value) {
            addCriterion("无节幼体 >", value, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体GreaterThanOrEqualTo(String value) {
            addCriterion("无节幼体 >=", value, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体LessThan(String value) {
            addCriterion("无节幼体 <", value, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体LessThanOrEqualTo(String value) {
            addCriterion("无节幼体 <=", value, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体Like(String value) {
            addCriterion("无节幼体 like", value, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体NotLike(String value) {
            addCriterion("无节幼体 not like", value, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体In(List<String> values) {
            addCriterion("无节幼体 in", values, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体NotIn(List<String> values) {
            addCriterion("无节幼体 not in", values, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体Between(String value1, String value2) {
            addCriterion("无节幼体 between", value1, value2, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and无节幼体NotBetween(String value1, String value2) {
            addCriterion("无节幼体 not between", value1, value2, "无节幼体");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤IsNull() {
            addCriterion("英勇剑水蚤 is null");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤IsNotNull() {
            addCriterion("英勇剑水蚤 is not null");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤EqualTo(String value) {
            addCriterion("英勇剑水蚤 =", value, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤NotEqualTo(String value) {
            addCriterion("英勇剑水蚤 <>", value, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤GreaterThan(String value) {
            addCriterion("英勇剑水蚤 >", value, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤GreaterThanOrEqualTo(String value) {
            addCriterion("英勇剑水蚤 >=", value, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤LessThan(String value) {
            addCriterion("英勇剑水蚤 <", value, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤LessThanOrEqualTo(String value) {
            addCriterion("英勇剑水蚤 <=", value, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤Like(String value) {
            addCriterion("英勇剑水蚤 like", value, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤NotLike(String value) {
            addCriterion("英勇剑水蚤 not like", value, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤In(List<String> values) {
            addCriterion("英勇剑水蚤 in", values, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤NotIn(List<String> values) {
            addCriterion("英勇剑水蚤 not in", values, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤Between(String value1, String value2) {
            addCriterion("英勇剑水蚤 between", value1, value2, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and英勇剑水蚤NotBetween(String value1, String value2) {
            addCriterion("英勇剑水蚤 not between", value1, value2, "英勇剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤IsNull() {
            addCriterion("透明温剑水蚤 is null");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤IsNotNull() {
            addCriterion("透明温剑水蚤 is not null");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤EqualTo(String value) {
            addCriterion("透明温剑水蚤 =", value, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤NotEqualTo(String value) {
            addCriterion("透明温剑水蚤 <>", value, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤GreaterThan(String value) {
            addCriterion("透明温剑水蚤 >", value, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤GreaterThanOrEqualTo(String value) {
            addCriterion("透明温剑水蚤 >=", value, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤LessThan(String value) {
            addCriterion("透明温剑水蚤 <", value, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤LessThanOrEqualTo(String value) {
            addCriterion("透明温剑水蚤 <=", value, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤Like(String value) {
            addCriterion("透明温剑水蚤 like", value, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤NotLike(String value) {
            addCriterion("透明温剑水蚤 not like", value, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤In(List<String> values) {
            addCriterion("透明温剑水蚤 in", values, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤NotIn(List<String> values) {
            addCriterion("透明温剑水蚤 not in", values, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤Between(String value1, String value2) {
            addCriterion("透明温剑水蚤 between", value1, value2, "透明温剑水蚤");
            return (Criteria) this;
        }

        public Criteria and透明温剑水蚤NotBetween(String value1, String value2) {
            addCriterion("透明温剑水蚤 not between", value1, value2, "透明温剑水蚤");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生多样性足类
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生多样性足类
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}