package com.glyk.heos.dal.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class 水生多样性原生动物Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public 水生多样性原生动物Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria and编号IsNull() {
            addCriterion("编号 is null");
            return (Criteria) this;
        }

        public Criteria and编号IsNotNull() {
            addCriterion("编号 is not null");
            return (Criteria) this;
        }

        public Criteria and编号EqualTo(String value) {
            addCriterion("编号 =", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotEqualTo(String value) {
            addCriterion("编号 <>", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThan(String value) {
            addCriterion("编号 >", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号GreaterThanOrEqualTo(String value) {
            addCriterion("编号 >=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThan(String value) {
            addCriterion("编号 <", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号LessThanOrEqualTo(String value) {
            addCriterion("编号 <=", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号Like(String value) {
            addCriterion("编号 like", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotLike(String value) {
            addCriterion("编号 not like", value, "编号");
            return (Criteria) this;
        }

        public Criteria and编号In(List<String> values) {
            addCriterion("编号 in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotIn(List<String> values) {
            addCriterion("编号 not in", values, "编号");
            return (Criteria) this;
        }

        public Criteria and编号Between(String value1, String value2) {
            addCriterion("编号 between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and编号NotBetween(String value1, String value2) {
            addCriterion("编号 not between", value1, value2, "编号");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNull() {
            addCriterion("采样点位 is null");
            return (Criteria) this;
        }

        public Criteria and采样点位IsNotNull() {
            addCriterion("采样点位 is not null");
            return (Criteria) this;
        }

        public Criteria and采样点位EqualTo(String value) {
            addCriterion("采样点位 =", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotEqualTo(String value) {
            addCriterion("采样点位 <>", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThan(String value) {
            addCriterion("采样点位 >", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位GreaterThanOrEqualTo(String value) {
            addCriterion("采样点位 >=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThan(String value) {
            addCriterion("采样点位 <", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位LessThanOrEqualTo(String value) {
            addCriterion("采样点位 <=", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Like(String value) {
            addCriterion("采样点位 like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotLike(String value) {
            addCriterion("采样点位 not like", value, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位In(List<String> values) {
            addCriterion("采样点位 in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotIn(List<String> values) {
            addCriterion("采样点位 not in", values, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位Between(String value1, String value2) {
            addCriterion("采样点位 between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and采样点位NotBetween(String value1, String value2) {
            addCriterion("采样点位 not between", value1, value2, "采样点位");
            return (Criteria) this;
        }

        public Criteria and日期IsNull() {
            addCriterion("日期 is null");
            return (Criteria) this;
        }

        public Criteria and日期IsNotNull() {
            addCriterion("日期 is not null");
            return (Criteria) this;
        }

        public Criteria and日期EqualTo(Date value) {
            addCriterionForJDBCDate("日期 =", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <>", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThan(Date value) {
            addCriterionForJDBCDate("日期 >", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 >=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThan(Date value) {
            addCriterionForJDBCDate("日期 <", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("日期 <=", value, "日期");
            return (Criteria) this;
        }

        public Criteria and日期In(List<Date> values) {
            addCriterionForJDBCDate("日期 in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotIn(List<Date> values) {
            addCriterionForJDBCDate("日期 not in", values, "日期");
            return (Criteria) this;
        }

        public Criteria and日期Between(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and日期NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("日期 not between", value1, value2, "日期");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫IsNull() {
            addCriterion("针棘匣壳虫 is null");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫IsNotNull() {
            addCriterion("针棘匣壳虫 is not null");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫EqualTo(String value) {
            addCriterion("针棘匣壳虫 =", value, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫NotEqualTo(String value) {
            addCriterion("针棘匣壳虫 <>", value, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫GreaterThan(String value) {
            addCriterion("针棘匣壳虫 >", value, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫GreaterThanOrEqualTo(String value) {
            addCriterion("针棘匣壳虫 >=", value, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫LessThan(String value) {
            addCriterion("针棘匣壳虫 <", value, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫LessThanOrEqualTo(String value) {
            addCriterion("针棘匣壳虫 <=", value, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫Like(String value) {
            addCriterion("针棘匣壳虫 like", value, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫NotLike(String value) {
            addCriterion("针棘匣壳虫 not like", value, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫In(List<String> values) {
            addCriterion("针棘匣壳虫 in", values, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫NotIn(List<String> values) {
            addCriterion("针棘匣壳虫 not in", values, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫Between(String value1, String value2) {
            addCriterion("针棘匣壳虫 between", value1, value2, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and针棘匣壳虫NotBetween(String value1, String value2) {
            addCriterion("针棘匣壳虫 not between", value1, value2, "针棘匣壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫IsNull() {
            addCriterion("王氏似铃壳虫 is null");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫IsNotNull() {
            addCriterion("王氏似铃壳虫 is not null");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫EqualTo(String value) {
            addCriterion("王氏似铃壳虫 =", value, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫NotEqualTo(String value) {
            addCriterion("王氏似铃壳虫 <>", value, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫GreaterThan(String value) {
            addCriterion("王氏似铃壳虫 >", value, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫GreaterThanOrEqualTo(String value) {
            addCriterion("王氏似铃壳虫 >=", value, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫LessThan(String value) {
            addCriterion("王氏似铃壳虫 <", value, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫LessThanOrEqualTo(String value) {
            addCriterion("王氏似铃壳虫 <=", value, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫Like(String value) {
            addCriterion("王氏似铃壳虫 like", value, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫NotLike(String value) {
            addCriterion("王氏似铃壳虫 not like", value, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫In(List<String> values) {
            addCriterion("王氏似铃壳虫 in", values, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫NotIn(List<String> values) {
            addCriterion("王氏似铃壳虫 not in", values, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫Between(String value1, String value2) {
            addCriterion("王氏似铃壳虫 between", value1, value2, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and王氏似铃壳虫NotBetween(String value1, String value2) {
            addCriterion("王氏似铃壳虫 not between", value1, value2, "王氏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫IsNull() {
            addCriterion("江苏似铃壳虫 is null");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫IsNotNull() {
            addCriterion("江苏似铃壳虫 is not null");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫EqualTo(String value) {
            addCriterion("江苏似铃壳虫 =", value, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫NotEqualTo(String value) {
            addCriterion("江苏似铃壳虫 <>", value, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫GreaterThan(String value) {
            addCriterion("江苏似铃壳虫 >", value, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫GreaterThanOrEqualTo(String value) {
            addCriterion("江苏似铃壳虫 >=", value, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫LessThan(String value) {
            addCriterion("江苏似铃壳虫 <", value, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫LessThanOrEqualTo(String value) {
            addCriterion("江苏似铃壳虫 <=", value, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫Like(String value) {
            addCriterion("江苏似铃壳虫 like", value, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫NotLike(String value) {
            addCriterion("江苏似铃壳虫 not like", value, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫In(List<String> values) {
            addCriterion("江苏似铃壳虫 in", values, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫NotIn(List<String> values) {
            addCriterion("江苏似铃壳虫 not in", values, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫Between(String value1, String value2) {
            addCriterion("江苏似铃壳虫 between", value1, value2, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and江苏似铃壳虫NotBetween(String value1, String value2) {
            addCriterion("江苏似铃壳虫 not between", value1, value2, "江苏似铃壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫IsNull() {
            addCriterion("普通表壳虫 is null");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫IsNotNull() {
            addCriterion("普通表壳虫 is not null");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫EqualTo(String value) {
            addCriterion("普通表壳虫 =", value, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫NotEqualTo(String value) {
            addCriterion("普通表壳虫 <>", value, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫GreaterThan(String value) {
            addCriterion("普通表壳虫 >", value, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫GreaterThanOrEqualTo(String value) {
            addCriterion("普通表壳虫 >=", value, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫LessThan(String value) {
            addCriterion("普通表壳虫 <", value, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫LessThanOrEqualTo(String value) {
            addCriterion("普通表壳虫 <=", value, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫Like(String value) {
            addCriterion("普通表壳虫 like", value, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫NotLike(String value) {
            addCriterion("普通表壳虫 not like", value, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫In(List<String> values) {
            addCriterion("普通表壳虫 in", values, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫NotIn(List<String> values) {
            addCriterion("普通表壳虫 not in", values, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫Between(String value1, String value2) {
            addCriterion("普通表壳虫 between", value1, value2, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and普通表壳虫NotBetween(String value1, String value2) {
            addCriterion("普通表壳虫 not between", value1, value2, "普通表壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫IsNull() {
            addCriterion("球砂壳虫 is null");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫IsNotNull() {
            addCriterion("球砂壳虫 is not null");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫EqualTo(String value) {
            addCriterion("球砂壳虫 =", value, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫NotEqualTo(String value) {
            addCriterion("球砂壳虫 <>", value, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫GreaterThan(String value) {
            addCriterion("球砂壳虫 >", value, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫GreaterThanOrEqualTo(String value) {
            addCriterion("球砂壳虫 >=", value, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫LessThan(String value) {
            addCriterion("球砂壳虫 <", value, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫LessThanOrEqualTo(String value) {
            addCriterion("球砂壳虫 <=", value, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫Like(String value) {
            addCriterion("球砂壳虫 like", value, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫NotLike(String value) {
            addCriterion("球砂壳虫 not like", value, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫In(List<String> values) {
            addCriterion("球砂壳虫 in", values, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫NotIn(List<String> values) {
            addCriterion("球砂壳虫 not in", values, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫Between(String value1, String value2) {
            addCriterion("球砂壳虫 between", value1, value2, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and球砂壳虫NotBetween(String value1, String value2) {
            addCriterion("球砂壳虫 not between", value1, value2, "球砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫IsNull() {
            addCriterion("尖顶砂壳虫 is null");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫IsNotNull() {
            addCriterion("尖顶砂壳虫 is not null");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫EqualTo(String value) {
            addCriterion("尖顶砂壳虫 =", value, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫NotEqualTo(String value) {
            addCriterion("尖顶砂壳虫 <>", value, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫GreaterThan(String value) {
            addCriterion("尖顶砂壳虫 >", value, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫GreaterThanOrEqualTo(String value) {
            addCriterion("尖顶砂壳虫 >=", value, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫LessThan(String value) {
            addCriterion("尖顶砂壳虫 <", value, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫LessThanOrEqualTo(String value) {
            addCriterion("尖顶砂壳虫 <=", value, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫Like(String value) {
            addCriterion("尖顶砂壳虫 like", value, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫NotLike(String value) {
            addCriterion("尖顶砂壳虫 not like", value, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫In(List<String> values) {
            addCriterion("尖顶砂壳虫 in", values, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫NotIn(List<String> values) {
            addCriterion("尖顶砂壳虫 not in", values, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫Between(String value1, String value2) {
            addCriterion("尖顶砂壳虫 between", value1, value2, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and尖顶砂壳虫NotBetween(String value1, String value2) {
            addCriterion("尖顶砂壳虫 not between", value1, value2, "尖顶砂壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫IsNull() {
            addCriterion("毛板壳虫 is null");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫IsNotNull() {
            addCriterion("毛板壳虫 is not null");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫EqualTo(String value) {
            addCriterion("毛板壳虫 =", value, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫NotEqualTo(String value) {
            addCriterion("毛板壳虫 <>", value, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫GreaterThan(String value) {
            addCriterion("毛板壳虫 >", value, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫GreaterThanOrEqualTo(String value) {
            addCriterion("毛板壳虫 >=", value, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫LessThan(String value) {
            addCriterion("毛板壳虫 <", value, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫LessThanOrEqualTo(String value) {
            addCriterion("毛板壳虫 <=", value, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫Like(String value) {
            addCriterion("毛板壳虫 like", value, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫NotLike(String value) {
            addCriterion("毛板壳虫 not like", value, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫In(List<String> values) {
            addCriterion("毛板壳虫 in", values, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫NotIn(List<String> values) {
            addCriterion("毛板壳虫 not in", values, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫Between(String value1, String value2) {
            addCriterion("毛板壳虫 between", value1, value2, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and毛板壳虫NotBetween(String value1, String value2) {
            addCriterion("毛板壳虫 not between", value1, value2, "毛板壳虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫IsNull() {
            addCriterion("小单环栉毛虫 is null");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫IsNotNull() {
            addCriterion("小单环栉毛虫 is not null");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫EqualTo(String value) {
            addCriterion("小单环栉毛虫 =", value, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫NotEqualTo(String value) {
            addCriterion("小单环栉毛虫 <>", value, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫GreaterThan(String value) {
            addCriterion("小单环栉毛虫 >", value, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫GreaterThanOrEqualTo(String value) {
            addCriterion("小单环栉毛虫 >=", value, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫LessThan(String value) {
            addCriterion("小单环栉毛虫 <", value, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫LessThanOrEqualTo(String value) {
            addCriterion("小单环栉毛虫 <=", value, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫Like(String value) {
            addCriterion("小单环栉毛虫 like", value, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫NotLike(String value) {
            addCriterion("小单环栉毛虫 not like", value, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫In(List<String> values) {
            addCriterion("小单环栉毛虫 in", values, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫NotIn(List<String> values) {
            addCriterion("小单环栉毛虫 not in", values, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫Between(String value1, String value2) {
            addCriterion("小单环栉毛虫 between", value1, value2, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and小单环栉毛虫NotBetween(String value1, String value2) {
            addCriterion("小单环栉毛虫 not between", value1, value2, "小单环栉毛虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫IsNull() {
            addCriterion("螅状独缩虫 is null");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫IsNotNull() {
            addCriterion("螅状独缩虫 is not null");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫EqualTo(String value) {
            addCriterion("螅状独缩虫 =", value, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫NotEqualTo(String value) {
            addCriterion("螅状独缩虫 <>", value, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫GreaterThan(String value) {
            addCriterion("螅状独缩虫 >", value, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫GreaterThanOrEqualTo(String value) {
            addCriterion("螅状独缩虫 >=", value, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫LessThan(String value) {
            addCriterion("螅状独缩虫 <", value, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫LessThanOrEqualTo(String value) {
            addCriterion("螅状独缩虫 <=", value, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫Like(String value) {
            addCriterion("螅状独缩虫 like", value, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫NotLike(String value) {
            addCriterion("螅状独缩虫 not like", value, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫In(List<String> values) {
            addCriterion("螅状独缩虫 in", values, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫NotIn(List<String> values) {
            addCriterion("螅状独缩虫 not in", values, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫Between(String value1, String value2) {
            addCriterion("螅状独缩虫 between", value1, value2, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and螅状独缩虫NotBetween(String value1, String value2) {
            addCriterion("螅状独缩虫 not between", value1, value2, "螅状独缩虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫IsNull() {
            addCriterion("坛状曲颈虫 is null");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫IsNotNull() {
            addCriterion("坛状曲颈虫 is not null");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫EqualTo(String value) {
            addCriterion("坛状曲颈虫 =", value, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫NotEqualTo(String value) {
            addCriterion("坛状曲颈虫 <>", value, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫GreaterThan(String value) {
            addCriterion("坛状曲颈虫 >", value, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫GreaterThanOrEqualTo(String value) {
            addCriterion("坛状曲颈虫 >=", value, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫LessThan(String value) {
            addCriterion("坛状曲颈虫 <", value, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫LessThanOrEqualTo(String value) {
            addCriterion("坛状曲颈虫 <=", value, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫Like(String value) {
            addCriterion("坛状曲颈虫 like", value, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫NotLike(String value) {
            addCriterion("坛状曲颈虫 not like", value, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫In(List<String> values) {
            addCriterion("坛状曲颈虫 in", values, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫NotIn(List<String> values) {
            addCriterion("坛状曲颈虫 not in", values, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫Between(String value1, String value2) {
            addCriterion("坛状曲颈虫 between", value1, value2, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and坛状曲颈虫NotBetween(String value1, String value2) {
            addCriterion("坛状曲颈虫 not between", value1, value2, "坛状曲颈虫");
            return (Criteria) this;
        }

        public Criteria and急游虫IsNull() {
            addCriterion("急游虫 is null");
            return (Criteria) this;
        }

        public Criteria and急游虫IsNotNull() {
            addCriterion("急游虫 is not null");
            return (Criteria) this;
        }

        public Criteria and急游虫EqualTo(String value) {
            addCriterion("急游虫 =", value, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫NotEqualTo(String value) {
            addCriterion("急游虫 <>", value, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫GreaterThan(String value) {
            addCriterion("急游虫 >", value, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫GreaterThanOrEqualTo(String value) {
            addCriterion("急游虫 >=", value, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫LessThan(String value) {
            addCriterion("急游虫 <", value, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫LessThanOrEqualTo(String value) {
            addCriterion("急游虫 <=", value, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫Like(String value) {
            addCriterion("急游虫 like", value, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫NotLike(String value) {
            addCriterion("急游虫 not like", value, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫In(List<String> values) {
            addCriterion("急游虫 in", values, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫NotIn(List<String> values) {
            addCriterion("急游虫 not in", values, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫Between(String value1, String value2) {
            addCriterion("急游虫 between", value1, value2, "急游虫");
            return (Criteria) this;
        }

        public Criteria and急游虫NotBetween(String value1, String value2) {
            addCriterion("急游虫 not between", value1, value2, "急游虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫IsNull() {
            addCriterion("砂壳虫 is null");
            return (Criteria) this;
        }

        public Criteria and砂壳虫IsNotNull() {
            addCriterion("砂壳虫 is not null");
            return (Criteria) this;
        }

        public Criteria and砂壳虫EqualTo(String value) {
            addCriterion("砂壳虫 =", value, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫NotEqualTo(String value) {
            addCriterion("砂壳虫 <>", value, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫GreaterThan(String value) {
            addCriterion("砂壳虫 >", value, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫GreaterThanOrEqualTo(String value) {
            addCriterion("砂壳虫 >=", value, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫LessThan(String value) {
            addCriterion("砂壳虫 <", value, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫LessThanOrEqualTo(String value) {
            addCriterion("砂壳虫 <=", value, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫Like(String value) {
            addCriterion("砂壳虫 like", value, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫NotLike(String value) {
            addCriterion("砂壳虫 not like", value, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫In(List<String> values) {
            addCriterion("砂壳虫 in", values, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫NotIn(List<String> values) {
            addCriterion("砂壳虫 not in", values, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫Between(String value1, String value2) {
            addCriterion("砂壳虫 between", value1, value2, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and砂壳虫NotBetween(String value1, String value2) {
            addCriterion("砂壳虫 not between", value1, value2, "砂壳虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫IsNull() {
            addCriterion("麻铃虫 is null");
            return (Criteria) this;
        }

        public Criteria and麻铃虫IsNotNull() {
            addCriterion("麻铃虫 is not null");
            return (Criteria) this;
        }

        public Criteria and麻铃虫EqualTo(String value) {
            addCriterion("麻铃虫 =", value, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫NotEqualTo(String value) {
            addCriterion("麻铃虫 <>", value, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫GreaterThan(String value) {
            addCriterion("麻铃虫 >", value, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫GreaterThanOrEqualTo(String value) {
            addCriterion("麻铃虫 >=", value, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫LessThan(String value) {
            addCriterion("麻铃虫 <", value, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫LessThanOrEqualTo(String value) {
            addCriterion("麻铃虫 <=", value, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫Like(String value) {
            addCriterion("麻铃虫 like", value, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫NotLike(String value) {
            addCriterion("麻铃虫 not like", value, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫In(List<String> values) {
            addCriterion("麻铃虫 in", values, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫NotIn(List<String> values) {
            addCriterion("麻铃虫 not in", values, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫Between(String value1, String value2) {
            addCriterion("麻铃虫 between", value1, value2, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and麻铃虫NotBetween(String value1, String value2) {
            addCriterion("麻铃虫 not between", value1, value2, "麻铃虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫IsNull() {
            addCriterion("侠盗虫 is null");
            return (Criteria) this;
        }

        public Criteria and侠盗虫IsNotNull() {
            addCriterion("侠盗虫 is not null");
            return (Criteria) this;
        }

        public Criteria and侠盗虫EqualTo(String value) {
            addCriterion("侠盗虫 =", value, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫NotEqualTo(String value) {
            addCriterion("侠盗虫 <>", value, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫GreaterThan(String value) {
            addCriterion("侠盗虫 >", value, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫GreaterThanOrEqualTo(String value) {
            addCriterion("侠盗虫 >=", value, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫LessThan(String value) {
            addCriterion("侠盗虫 <", value, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫LessThanOrEqualTo(String value) {
            addCriterion("侠盗虫 <=", value, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫Like(String value) {
            addCriterion("侠盗虫 like", value, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫NotLike(String value) {
            addCriterion("侠盗虫 not like", value, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫In(List<String> values) {
            addCriterion("侠盗虫 in", values, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫NotIn(List<String> values) {
            addCriterion("侠盗虫 not in", values, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫Between(String value1, String value2) {
            addCriterion("侠盗虫 between", value1, value2, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and侠盗虫NotBetween(String value1, String value2) {
            addCriterion("侠盗虫 not between", value1, value2, "侠盗虫");
            return (Criteria) this;
        }

        public Criteria and钟虫IsNull() {
            addCriterion("钟虫 is null");
            return (Criteria) this;
        }

        public Criteria and钟虫IsNotNull() {
            addCriterion("钟虫 is not null");
            return (Criteria) this;
        }

        public Criteria and钟虫EqualTo(String value) {
            addCriterion("钟虫 =", value, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫NotEqualTo(String value) {
            addCriterion("钟虫 <>", value, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫GreaterThan(String value) {
            addCriterion("钟虫 >", value, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫GreaterThanOrEqualTo(String value) {
            addCriterion("钟虫 >=", value, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫LessThan(String value) {
            addCriterion("钟虫 <", value, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫LessThanOrEqualTo(String value) {
            addCriterion("钟虫 <=", value, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫Like(String value) {
            addCriterion("钟虫 like", value, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫NotLike(String value) {
            addCriterion("钟虫 not like", value, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫In(List<String> values) {
            addCriterion("钟虫 in", values, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫NotIn(List<String> values) {
            addCriterion("钟虫 not in", values, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫Between(String value1, String value2) {
            addCriterion("钟虫 between", value1, value2, "钟虫");
            return (Criteria) this;
        }

        public Criteria and钟虫NotBetween(String value1, String value2) {
            addCriterion("钟虫 not between", value1, value2, "钟虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫IsNull() {
            addCriterion("纤毛虫 is null");
            return (Criteria) this;
        }

        public Criteria and纤毛虫IsNotNull() {
            addCriterion("纤毛虫 is not null");
            return (Criteria) this;
        }

        public Criteria and纤毛虫EqualTo(String value) {
            addCriterion("纤毛虫 =", value, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫NotEqualTo(String value) {
            addCriterion("纤毛虫 <>", value, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫GreaterThan(String value) {
            addCriterion("纤毛虫 >", value, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫GreaterThanOrEqualTo(String value) {
            addCriterion("纤毛虫 >=", value, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫LessThan(String value) {
            addCriterion("纤毛虫 <", value, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫LessThanOrEqualTo(String value) {
            addCriterion("纤毛虫 <=", value, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫Like(String value) {
            addCriterion("纤毛虫 like", value, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫NotLike(String value) {
            addCriterion("纤毛虫 not like", value, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫In(List<String> values) {
            addCriterion("纤毛虫 in", values, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫NotIn(List<String> values) {
            addCriterion("纤毛虫 not in", values, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫Between(String value1, String value2) {
            addCriterion("纤毛虫 between", value1, value2, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and纤毛虫NotBetween(String value1, String value2) {
            addCriterion("纤毛虫 not between", value1, value2, "纤毛虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫IsNull() {
            addCriterion("累枝虫 is null");
            return (Criteria) this;
        }

        public Criteria and累枝虫IsNotNull() {
            addCriterion("累枝虫 is not null");
            return (Criteria) this;
        }

        public Criteria and累枝虫EqualTo(String value) {
            addCriterion("累枝虫 =", value, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫NotEqualTo(String value) {
            addCriterion("累枝虫 <>", value, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫GreaterThan(String value) {
            addCriterion("累枝虫 >", value, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫GreaterThanOrEqualTo(String value) {
            addCriterion("累枝虫 >=", value, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫LessThan(String value) {
            addCriterion("累枝虫 <", value, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫LessThanOrEqualTo(String value) {
            addCriterion("累枝虫 <=", value, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫Like(String value) {
            addCriterion("累枝虫 like", value, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫NotLike(String value) {
            addCriterion("累枝虫 not like", value, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫In(List<String> values) {
            addCriterion("累枝虫 in", values, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫NotIn(List<String> values) {
            addCriterion("累枝虫 not in", values, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫Between(String value1, String value2) {
            addCriterion("累枝虫 between", value1, value2, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and累枝虫NotBetween(String value1, String value2) {
            addCriterion("累枝虫 not between", value1, value2, "累枝虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫IsNull() {
            addCriterion("喇叭虫 is null");
            return (Criteria) this;
        }

        public Criteria and喇叭虫IsNotNull() {
            addCriterion("喇叭虫 is not null");
            return (Criteria) this;
        }

        public Criteria and喇叭虫EqualTo(String value) {
            addCriterion("喇叭虫 =", value, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫NotEqualTo(String value) {
            addCriterion("喇叭虫 <>", value, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫GreaterThan(String value) {
            addCriterion("喇叭虫 >", value, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫GreaterThanOrEqualTo(String value) {
            addCriterion("喇叭虫 >=", value, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫LessThan(String value) {
            addCriterion("喇叭虫 <", value, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫LessThanOrEqualTo(String value) {
            addCriterion("喇叭虫 <=", value, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫Like(String value) {
            addCriterion("喇叭虫 like", value, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫NotLike(String value) {
            addCriterion("喇叭虫 not like", value, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫In(List<String> values) {
            addCriterion("喇叭虫 in", values, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫NotIn(List<String> values) {
            addCriterion("喇叭虫 not in", values, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫Between(String value1, String value2) {
            addCriterion("喇叭虫 between", value1, value2, "喇叭虫");
            return (Criteria) this;
        }

        public Criteria and喇叭虫NotBetween(String value1, String value2) {
            addCriterion("喇叭虫 not between", value1, value2, "喇叭虫");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 水生多样性原生动物
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}