package com.glyk.heos.dal.dao;

import com.glyk.heos.dal.dao.水质监测地址;
import com.glyk.heos.dal.dao.水质监测地址Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface 水质监测地址Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    long countByExample(水质监测地址Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    int deleteByExample(水质监测地址Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    int insert(水质监测地址 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    int insertSelective(水质监测地址 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    List<水质监测地址> selectByExample(水质监测地址Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    水质监测地址 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") 水质监测地址 record, @Param("example") 水质监测地址Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") 水质监测地址 record, @Param("example") 水质监测地址Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(水质监测地址 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 水质监测地址
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(水质监测地址 record);
}