package com.glyk.heos.dal.dao;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class 生物群落201809bacteria {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.编号
     *
     * @mbg.generated
     */
    private String 编号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.采样点位
     *
     * @mbg.generated
     */
    private String 采样点位;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.日期
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM",timezone = "GMT+8")
    private Date 日期;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Altiarchaeota
     *
     * @mbg.generated
     */
    private String altiarchaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Asgardaeota
     *
     * @mbg.generated
     */
    private String asgardaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Crenarchaeota
     *
     * @mbg.generated
     */
    private String crenarchaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Diapherotrites
     *
     * @mbg.generated
     */
    private String diapherotrites;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Euryarchaeota
     *
     * @mbg.generated
     */
    private String euryarchaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Nanoarchaeaeota
     *
     * @mbg.generated
     */
    private String nanoarchaeaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Thaumarchaeota
     *
     * @mbg.generated
     */
    private String thaumarchaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Acetothermia
     *
     * @mbg.generated
     */
    private String acetothermia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Acidobacteria
     *
     * @mbg.generated
     */
    private String acidobacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Actinobacteria
     *
     * @mbg.generated
     */
    private String actinobacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.AncK6
     *
     * @mbg.generated
     */
    private String anck6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Armatimonadetes
     *
     * @mbg.generated
     */
    private String armatimonadetes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Atribacteria
     *
     * @mbg.generated
     */
    private String atribacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Bacteroidetes
     *
     * @mbg.generated
     */
    private String bacteroidetes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.BRC1
     *
     * @mbg.generated
     */
    private String brc1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Caldiserica
     *
     * @mbg.generated
     */
    private String caldiserica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Calditrichaeota
     *
     * @mbg.generated
     */
    private String calditrichaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Chlamydiae
     *
     * @mbg.generated
     */
    private String chlamydiae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Chloroflexi
     *
     * @mbg.generated
     */
    private String chloroflexi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Cloacimonetes
     *
     * @mbg.generated
     */
    private String cloacimonetes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Cyanobacteria
     *
     * @mbg.generated
     */
    private String cyanobacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Dadabacteria
     *
     * @mbg.generated
     */
    private String dadabacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Deinococcus-Thermus
     *
     * @mbg.generated
     */
    private String deinococcusThermus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Dependentiae
     *
     * @mbg.generated
     */
    private String dependentiae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Elusimicrobia
     *
     * @mbg.generated
     */
    private String elusimicrobia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Entotheonellaeota
     *
     * @mbg.generated
     */
    private String entotheonellaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Epsilonbacteraeota
     *
     * @mbg.generated
     */
    private String epsilonbacteraeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.FBP
     *
     * @mbg.generated
     */
    private String fbp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.FCPU426
     *
     * @mbg.generated
     */
    private String fcpu426;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Fibrobacteres
     *
     * @mbg.generated
     */
    private String fibrobacteres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Firmicutes
     *
     * @mbg.generated
     */
    private String firmicutes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Fusobacteria
     *
     * @mbg.generated
     */
    private String fusobacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.GAL15
     *
     * @mbg.generated
     */
    private String gal15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Gemmatimonadetes
     *
     * @mbg.generated
     */
    private String gemmatimonadetes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Hydrogenedentes
     *
     * @mbg.generated
     */
    private String hydrogenedentes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Kiritimatiellaeota
     *
     * @mbg.generated
     */
    private String kiritimatiellaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Latescibacteria
     *
     * @mbg.generated
     */
    private String latescibacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.LCP-89
     *
     * @mbg.generated
     */
    private String lcp89;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Lentisphaerae
     *
     * @mbg.generated
     */
    private String lentisphaerae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Margulisbacteria
     *
     * @mbg.generated
     */
    private String margulisbacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.MAT_CR_M4_B07
     *
     * @mbg.generated
     */
    private String matCrM4B07;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Nitrospinae
     *
     * @mbg.generated
     */
    private String nitrospinae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Nitrospirae
     *
     * @mbg.generated
     */
    private String nitrospirae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Omnitrophicaeota
     *
     * @mbg.generated
     */
    private String omnitrophicaeota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Patescibacteria
     *
     * @mbg.generated
     */
    private String patescibacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.PAUC34f
     *
     * @mbg.generated
     */
    private String pauc34f;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Planctomycetes
     *
     * @mbg.generated
     */
    private String planctomycetes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Proteobacteria
     *
     * @mbg.generated
     */
    private String proteobacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Rokubacteria
     *
     * @mbg.generated
     */
    private String rokubacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Spirochaetes
     *
     * @mbg.generated
     */
    private String spirochaetes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Synergistetes
     *
     * @mbg.generated
     */
    private String synergistetes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.TA06
     *
     * @mbg.generated
     */
    private String ta06;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Tenericutes
     *
     * @mbg.generated
     */
    private String tenericutes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Thermotogae
     *
     * @mbg.generated
     */
    private String thermotogae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Verrucomicrobia
     *
     * @mbg.generated
     */
    private String verrucomicrobia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.WPS-2
     *
     * @mbg.generated
     */
    private String wps2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.WS1
     *
     * @mbg.generated
     */
    private String ws1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.Zixibacteria
     *
     * @mbg.generated
     */
    private String zixibacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 生物群落201809bacteria.empty
     *
     * @mbg.generated
     */
    private String empty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.ID
     *
     * @return the value of 生物群落201809bacteria.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.ID
     *
     * @param id the value for 生物群落201809bacteria.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.编号
     *
     * @return the value of 生物群落201809bacteria.编号
     *
     * @mbg.generated
     */
    public String get编号() {
        return 编号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.编号
     *
     * @param 编号 the value for 生物群落201809bacteria.编号
     *
     * @mbg.generated
     */
    public void set编号(String 编号) {
        this.编号 = 编号 == null ? null : 编号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.采样点位
     *
     * @return the value of 生物群落201809bacteria.采样点位
     *
     * @mbg.generated
     */
    public String get采样点位() {
        return 采样点位;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.采样点位
     *
     * @param 采样点位 the value for 生物群落201809bacteria.采样点位
     *
     * @mbg.generated
     */
    public void set采样点位(String 采样点位) {
        this.采样点位 = 采样点位 == null ? null : 采样点位.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.日期
     *
     * @return the value of 生物群落201809bacteria.日期
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM",timezone = "GMT+8")
    public Date get日期() {
        return 日期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.日期
     *
     * @param 日期 the value for 生物群落201809bacteria.日期
     *
     * @mbg.generated
     */
    public void set日期(Date 日期) {
        this.日期 = 日期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Altiarchaeota
     *
     * @return the value of 生物群落201809bacteria.Altiarchaeota
     *
     * @mbg.generated
     */
    public String getAltiarchaeota() {
        return altiarchaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Altiarchaeota
     *
     * @param altiarchaeota the value for 生物群落201809bacteria.Altiarchaeota
     *
     * @mbg.generated
     */
    public void setAltiarchaeota(String altiarchaeota) {
        this.altiarchaeota = altiarchaeota == null ? null : altiarchaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Asgardaeota
     *
     * @return the value of 生物群落201809bacteria.Asgardaeota
     *
     * @mbg.generated
     */
    public String getAsgardaeota() {
        return asgardaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Asgardaeota
     *
     * @param asgardaeota the value for 生物群落201809bacteria.Asgardaeota
     *
     * @mbg.generated
     */
    public void setAsgardaeota(String asgardaeota) {
        this.asgardaeota = asgardaeota == null ? null : asgardaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Crenarchaeota
     *
     * @return the value of 生物群落201809bacteria.Crenarchaeota
     *
     * @mbg.generated
     */
    public String getCrenarchaeota() {
        return crenarchaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Crenarchaeota
     *
     * @param crenarchaeota the value for 生物群落201809bacteria.Crenarchaeota
     *
     * @mbg.generated
     */
    public void setCrenarchaeota(String crenarchaeota) {
        this.crenarchaeota = crenarchaeota == null ? null : crenarchaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Diapherotrites
     *
     * @return the value of 生物群落201809bacteria.Diapherotrites
     *
     * @mbg.generated
     */
    public String getDiapherotrites() {
        return diapherotrites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Diapherotrites
     *
     * @param diapherotrites the value for 生物群落201809bacteria.Diapherotrites
     *
     * @mbg.generated
     */
    public void setDiapherotrites(String diapherotrites) {
        this.diapherotrites = diapherotrites == null ? null : diapherotrites.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Euryarchaeota
     *
     * @return the value of 生物群落201809bacteria.Euryarchaeota
     *
     * @mbg.generated
     */
    public String getEuryarchaeota() {
        return euryarchaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Euryarchaeota
     *
     * @param euryarchaeota the value for 生物群落201809bacteria.Euryarchaeota
     *
     * @mbg.generated
     */
    public void setEuryarchaeota(String euryarchaeota) {
        this.euryarchaeota = euryarchaeota == null ? null : euryarchaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Nanoarchaeaeota
     *
     * @return the value of 生物群落201809bacteria.Nanoarchaeaeota
     *
     * @mbg.generated
     */
    public String getNanoarchaeaeota() {
        return nanoarchaeaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Nanoarchaeaeota
     *
     * @param nanoarchaeaeota the value for 生物群落201809bacteria.Nanoarchaeaeota
     *
     * @mbg.generated
     */
    public void setNanoarchaeaeota(String nanoarchaeaeota) {
        this.nanoarchaeaeota = nanoarchaeaeota == null ? null : nanoarchaeaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Thaumarchaeota
     *
     * @return the value of 生物群落201809bacteria.Thaumarchaeota
     *
     * @mbg.generated
     */
    public String getThaumarchaeota() {
        return thaumarchaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Thaumarchaeota
     *
     * @param thaumarchaeota the value for 生物群落201809bacteria.Thaumarchaeota
     *
     * @mbg.generated
     */
    public void setThaumarchaeota(String thaumarchaeota) {
        this.thaumarchaeota = thaumarchaeota == null ? null : thaumarchaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Acetothermia
     *
     * @return the value of 生物群落201809bacteria.Acetothermia
     *
     * @mbg.generated
     */
    public String getAcetothermia() {
        return acetothermia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Acetothermia
     *
     * @param acetothermia the value for 生物群落201809bacteria.Acetothermia
     *
     * @mbg.generated
     */
    public void setAcetothermia(String acetothermia) {
        this.acetothermia = acetothermia == null ? null : acetothermia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Acidobacteria
     *
     * @return the value of 生物群落201809bacteria.Acidobacteria
     *
     * @mbg.generated
     */
    public String getAcidobacteria() {
        return acidobacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Acidobacteria
     *
     * @param acidobacteria the value for 生物群落201809bacteria.Acidobacteria
     *
     * @mbg.generated
     */
    public void setAcidobacteria(String acidobacteria) {
        this.acidobacteria = acidobacteria == null ? null : acidobacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Actinobacteria
     *
     * @return the value of 生物群落201809bacteria.Actinobacteria
     *
     * @mbg.generated
     */
    public String getActinobacteria() {
        return actinobacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Actinobacteria
     *
     * @param actinobacteria the value for 生物群落201809bacteria.Actinobacteria
     *
     * @mbg.generated
     */
    public void setActinobacteria(String actinobacteria) {
        this.actinobacteria = actinobacteria == null ? null : actinobacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.AncK6
     *
     * @return the value of 生物群落201809bacteria.AncK6
     *
     * @mbg.generated
     */
    public String getAnck6() {
        return anck6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.AncK6
     *
     * @param anck6 the value for 生物群落201809bacteria.AncK6
     *
     * @mbg.generated
     */
    public void setAnck6(String anck6) {
        this.anck6 = anck6 == null ? null : anck6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Armatimonadetes
     *
     * @return the value of 生物群落201809bacteria.Armatimonadetes
     *
     * @mbg.generated
     */
    public String getArmatimonadetes() {
        return armatimonadetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Armatimonadetes
     *
     * @param armatimonadetes the value for 生物群落201809bacteria.Armatimonadetes
     *
     * @mbg.generated
     */
    public void setArmatimonadetes(String armatimonadetes) {
        this.armatimonadetes = armatimonadetes == null ? null : armatimonadetes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Atribacteria
     *
     * @return the value of 生物群落201809bacteria.Atribacteria
     *
     * @mbg.generated
     */
    public String getAtribacteria() {
        return atribacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Atribacteria
     *
     * @param atribacteria the value for 生物群落201809bacteria.Atribacteria
     *
     * @mbg.generated
     */
    public void setAtribacteria(String atribacteria) {
        this.atribacteria = atribacteria == null ? null : atribacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Bacteroidetes
     *
     * @return the value of 生物群落201809bacteria.Bacteroidetes
     *
     * @mbg.generated
     */
    public String getBacteroidetes() {
        return bacteroidetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Bacteroidetes
     *
     * @param bacteroidetes the value for 生物群落201809bacteria.Bacteroidetes
     *
     * @mbg.generated
     */
    public void setBacteroidetes(String bacteroidetes) {
        this.bacteroidetes = bacteroidetes == null ? null : bacteroidetes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.BRC1
     *
     * @return the value of 生物群落201809bacteria.BRC1
     *
     * @mbg.generated
     */
    public String getBrc1() {
        return brc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.BRC1
     *
     * @param brc1 the value for 生物群落201809bacteria.BRC1
     *
     * @mbg.generated
     */
    public void setBrc1(String brc1) {
        this.brc1 = brc1 == null ? null : brc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Caldiserica
     *
     * @return the value of 生物群落201809bacteria.Caldiserica
     *
     * @mbg.generated
     */
    public String getCaldiserica() {
        return caldiserica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Caldiserica
     *
     * @param caldiserica the value for 生物群落201809bacteria.Caldiserica
     *
     * @mbg.generated
     */
    public void setCaldiserica(String caldiserica) {
        this.caldiserica = caldiserica == null ? null : caldiserica.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Calditrichaeota
     *
     * @return the value of 生物群落201809bacteria.Calditrichaeota
     *
     * @mbg.generated
     */
    public String getCalditrichaeota() {
        return calditrichaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Calditrichaeota
     *
     * @param calditrichaeota the value for 生物群落201809bacteria.Calditrichaeota
     *
     * @mbg.generated
     */
    public void setCalditrichaeota(String calditrichaeota) {
        this.calditrichaeota = calditrichaeota == null ? null : calditrichaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Chlamydiae
     *
     * @return the value of 生物群落201809bacteria.Chlamydiae
     *
     * @mbg.generated
     */
    public String getChlamydiae() {
        return chlamydiae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Chlamydiae
     *
     * @param chlamydiae the value for 生物群落201809bacteria.Chlamydiae
     *
     * @mbg.generated
     */
    public void setChlamydiae(String chlamydiae) {
        this.chlamydiae = chlamydiae == null ? null : chlamydiae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Chloroflexi
     *
     * @return the value of 生物群落201809bacteria.Chloroflexi
     *
     * @mbg.generated
     */
    public String getChloroflexi() {
        return chloroflexi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Chloroflexi
     *
     * @param chloroflexi the value for 生物群落201809bacteria.Chloroflexi
     *
     * @mbg.generated
     */
    public void setChloroflexi(String chloroflexi) {
        this.chloroflexi = chloroflexi == null ? null : chloroflexi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Cloacimonetes
     *
     * @return the value of 生物群落201809bacteria.Cloacimonetes
     *
     * @mbg.generated
     */
    public String getCloacimonetes() {
        return cloacimonetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Cloacimonetes
     *
     * @param cloacimonetes the value for 生物群落201809bacteria.Cloacimonetes
     *
     * @mbg.generated
     */
    public void setCloacimonetes(String cloacimonetes) {
        this.cloacimonetes = cloacimonetes == null ? null : cloacimonetes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Cyanobacteria
     *
     * @return the value of 生物群落201809bacteria.Cyanobacteria
     *
     * @mbg.generated
     */
    public String getCyanobacteria() {
        return cyanobacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Cyanobacteria
     *
     * @param cyanobacteria the value for 生物群落201809bacteria.Cyanobacteria
     *
     * @mbg.generated
     */
    public void setCyanobacteria(String cyanobacteria) {
        this.cyanobacteria = cyanobacteria == null ? null : cyanobacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Dadabacteria
     *
     * @return the value of 生物群落201809bacteria.Dadabacteria
     *
     * @mbg.generated
     */
    public String getDadabacteria() {
        return dadabacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Dadabacteria
     *
     * @param dadabacteria the value for 生物群落201809bacteria.Dadabacteria
     *
     * @mbg.generated
     */
    public void setDadabacteria(String dadabacteria) {
        this.dadabacteria = dadabacteria == null ? null : dadabacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Deinococcus-Thermus
     *
     * @return the value of 生物群落201809bacteria.Deinococcus-Thermus
     *
     * @mbg.generated
     */
    public String getDeinococcusThermus() {
        return deinococcusThermus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Deinococcus-Thermus
     *
     * @param deinococcusThermus the value for 生物群落201809bacteria.Deinococcus-Thermus
     *
     * @mbg.generated
     */
    public void setDeinococcusThermus(String deinococcusThermus) {
        this.deinococcusThermus = deinococcusThermus == null ? null : deinococcusThermus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Dependentiae
     *
     * @return the value of 生物群落201809bacteria.Dependentiae
     *
     * @mbg.generated
     */
    public String getDependentiae() {
        return dependentiae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Dependentiae
     *
     * @param dependentiae the value for 生物群落201809bacteria.Dependentiae
     *
     * @mbg.generated
     */
    public void setDependentiae(String dependentiae) {
        this.dependentiae = dependentiae == null ? null : dependentiae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Elusimicrobia
     *
     * @return the value of 生物群落201809bacteria.Elusimicrobia
     *
     * @mbg.generated
     */
    public String getElusimicrobia() {
        return elusimicrobia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Elusimicrobia
     *
     * @param elusimicrobia the value for 生物群落201809bacteria.Elusimicrobia
     *
     * @mbg.generated
     */
    public void setElusimicrobia(String elusimicrobia) {
        this.elusimicrobia = elusimicrobia == null ? null : elusimicrobia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Entotheonellaeota
     *
     * @return the value of 生物群落201809bacteria.Entotheonellaeota
     *
     * @mbg.generated
     */
    public String getEntotheonellaeota() {
        return entotheonellaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Entotheonellaeota
     *
     * @param entotheonellaeota the value for 生物群落201809bacteria.Entotheonellaeota
     *
     * @mbg.generated
     */
    public void setEntotheonellaeota(String entotheonellaeota) {
        this.entotheonellaeota = entotheonellaeota == null ? null : entotheonellaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Epsilonbacteraeota
     *
     * @return the value of 生物群落201809bacteria.Epsilonbacteraeota
     *
     * @mbg.generated
     */
    public String getEpsilonbacteraeota() {
        return epsilonbacteraeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Epsilonbacteraeota
     *
     * @param epsilonbacteraeota the value for 生物群落201809bacteria.Epsilonbacteraeota
     *
     * @mbg.generated
     */
    public void setEpsilonbacteraeota(String epsilonbacteraeota) {
        this.epsilonbacteraeota = epsilonbacteraeota == null ? null : epsilonbacteraeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.FBP
     *
     * @return the value of 生物群落201809bacteria.FBP
     *
     * @mbg.generated
     */
    public String getFbp() {
        return fbp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.FBP
     *
     * @param fbp the value for 生物群落201809bacteria.FBP
     *
     * @mbg.generated
     */
    public void setFbp(String fbp) {
        this.fbp = fbp == null ? null : fbp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.FCPU426
     *
     * @return the value of 生物群落201809bacteria.FCPU426
     *
     * @mbg.generated
     */
    public String getFcpu426() {
        return fcpu426;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.FCPU426
     *
     * @param fcpu426 the value for 生物群落201809bacteria.FCPU426
     *
     * @mbg.generated
     */
    public void setFcpu426(String fcpu426) {
        this.fcpu426 = fcpu426 == null ? null : fcpu426.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Fibrobacteres
     *
     * @return the value of 生物群落201809bacteria.Fibrobacteres
     *
     * @mbg.generated
     */
    public String getFibrobacteres() {
        return fibrobacteres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Fibrobacteres
     *
     * @param fibrobacteres the value for 生物群落201809bacteria.Fibrobacteres
     *
     * @mbg.generated
     */
    public void setFibrobacteres(String fibrobacteres) {
        this.fibrobacteres = fibrobacteres == null ? null : fibrobacteres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Firmicutes
     *
     * @return the value of 生物群落201809bacteria.Firmicutes
     *
     * @mbg.generated
     */
    public String getFirmicutes() {
        return firmicutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Firmicutes
     *
     * @param firmicutes the value for 生物群落201809bacteria.Firmicutes
     *
     * @mbg.generated
     */
    public void setFirmicutes(String firmicutes) {
        this.firmicutes = firmicutes == null ? null : firmicutes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Fusobacteria
     *
     * @return the value of 生物群落201809bacteria.Fusobacteria
     *
     * @mbg.generated
     */
    public String getFusobacteria() {
        return fusobacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Fusobacteria
     *
     * @param fusobacteria the value for 生物群落201809bacteria.Fusobacteria
     *
     * @mbg.generated
     */
    public void setFusobacteria(String fusobacteria) {
        this.fusobacteria = fusobacteria == null ? null : fusobacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.GAL15
     *
     * @return the value of 生物群落201809bacteria.GAL15
     *
     * @mbg.generated
     */
    public String getGal15() {
        return gal15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.GAL15
     *
     * @param gal15 the value for 生物群落201809bacteria.GAL15
     *
     * @mbg.generated
     */
    public void setGal15(String gal15) {
        this.gal15 = gal15 == null ? null : gal15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Gemmatimonadetes
     *
     * @return the value of 生物群落201809bacteria.Gemmatimonadetes
     *
     * @mbg.generated
     */
    public String getGemmatimonadetes() {
        return gemmatimonadetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Gemmatimonadetes
     *
     * @param gemmatimonadetes the value for 生物群落201809bacteria.Gemmatimonadetes
     *
     * @mbg.generated
     */
    public void setGemmatimonadetes(String gemmatimonadetes) {
        this.gemmatimonadetes = gemmatimonadetes == null ? null : gemmatimonadetes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Hydrogenedentes
     *
     * @return the value of 生物群落201809bacteria.Hydrogenedentes
     *
     * @mbg.generated
     */
    public String getHydrogenedentes() {
        return hydrogenedentes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Hydrogenedentes
     *
     * @param hydrogenedentes the value for 生物群落201809bacteria.Hydrogenedentes
     *
     * @mbg.generated
     */
    public void setHydrogenedentes(String hydrogenedentes) {
        this.hydrogenedentes = hydrogenedentes == null ? null : hydrogenedentes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Kiritimatiellaeota
     *
     * @return the value of 生物群落201809bacteria.Kiritimatiellaeota
     *
     * @mbg.generated
     */
    public String getKiritimatiellaeota() {
        return kiritimatiellaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Kiritimatiellaeota
     *
     * @param kiritimatiellaeota the value for 生物群落201809bacteria.Kiritimatiellaeota
     *
     * @mbg.generated
     */
    public void setKiritimatiellaeota(String kiritimatiellaeota) {
        this.kiritimatiellaeota = kiritimatiellaeota == null ? null : kiritimatiellaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Latescibacteria
     *
     * @return the value of 生物群落201809bacteria.Latescibacteria
     *
     * @mbg.generated
     */
    public String getLatescibacteria() {
        return latescibacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Latescibacteria
     *
     * @param latescibacteria the value for 生物群落201809bacteria.Latescibacteria
     *
     * @mbg.generated
     */
    public void setLatescibacteria(String latescibacteria) {
        this.latescibacteria = latescibacteria == null ? null : latescibacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.LCP-89
     *
     * @return the value of 生物群落201809bacteria.LCP-89
     *
     * @mbg.generated
     */
    public String getLcp89() {
        return lcp89;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.LCP-89
     *
     * @param lcp89 the value for 生物群落201809bacteria.LCP-89
     *
     * @mbg.generated
     */
    public void setLcp89(String lcp89) {
        this.lcp89 = lcp89 == null ? null : lcp89.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Lentisphaerae
     *
     * @return the value of 生物群落201809bacteria.Lentisphaerae
     *
     * @mbg.generated
     */
    public String getLentisphaerae() {
        return lentisphaerae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Lentisphaerae
     *
     * @param lentisphaerae the value for 生物群落201809bacteria.Lentisphaerae
     *
     * @mbg.generated
     */
    public void setLentisphaerae(String lentisphaerae) {
        this.lentisphaerae = lentisphaerae == null ? null : lentisphaerae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Margulisbacteria
     *
     * @return the value of 生物群落201809bacteria.Margulisbacteria
     *
     * @mbg.generated
     */
    public String getMargulisbacteria() {
        return margulisbacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Margulisbacteria
     *
     * @param margulisbacteria the value for 生物群落201809bacteria.Margulisbacteria
     *
     * @mbg.generated
     */
    public void setMargulisbacteria(String margulisbacteria) {
        this.margulisbacteria = margulisbacteria == null ? null : margulisbacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.MAT_CR_M4_B07
     *
     * @return the value of 生物群落201809bacteria.MAT_CR_M4_B07
     *
     * @mbg.generated
     */
    public String getMatCrM4B07() {
        return matCrM4B07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.MAT_CR_M4_B07
     *
     * @param matCrM4B07 the value for 生物群落201809bacteria.MAT_CR_M4_B07
     *
     * @mbg.generated
     */
    public void setMatCrM4B07(String matCrM4B07) {
        this.matCrM4B07 = matCrM4B07 == null ? null : matCrM4B07.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Nitrospinae
     *
     * @return the value of 生物群落201809bacteria.Nitrospinae
     *
     * @mbg.generated
     */
    public String getNitrospinae() {
        return nitrospinae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Nitrospinae
     *
     * @param nitrospinae the value for 生物群落201809bacteria.Nitrospinae
     *
     * @mbg.generated
     */
    public void setNitrospinae(String nitrospinae) {
        this.nitrospinae = nitrospinae == null ? null : nitrospinae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Nitrospirae
     *
     * @return the value of 生物群落201809bacteria.Nitrospirae
     *
     * @mbg.generated
     */
    public String getNitrospirae() {
        return nitrospirae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Nitrospirae
     *
     * @param nitrospirae the value for 生物群落201809bacteria.Nitrospirae
     *
     * @mbg.generated
     */
    public void setNitrospirae(String nitrospirae) {
        this.nitrospirae = nitrospirae == null ? null : nitrospirae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Omnitrophicaeota
     *
     * @return the value of 生物群落201809bacteria.Omnitrophicaeota
     *
     * @mbg.generated
     */
    public String getOmnitrophicaeota() {
        return omnitrophicaeota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Omnitrophicaeota
     *
     * @param omnitrophicaeota the value for 生物群落201809bacteria.Omnitrophicaeota
     *
     * @mbg.generated
     */
    public void setOmnitrophicaeota(String omnitrophicaeota) {
        this.omnitrophicaeota = omnitrophicaeota == null ? null : omnitrophicaeota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Patescibacteria
     *
     * @return the value of 生物群落201809bacteria.Patescibacteria
     *
     * @mbg.generated
     */
    public String getPatescibacteria() {
        return patescibacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Patescibacteria
     *
     * @param patescibacteria the value for 生物群落201809bacteria.Patescibacteria
     *
     * @mbg.generated
     */
    public void setPatescibacteria(String patescibacteria) {
        this.patescibacteria = patescibacteria == null ? null : patescibacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.PAUC34f
     *
     * @return the value of 生物群落201809bacteria.PAUC34f
     *
     * @mbg.generated
     */
    public String getPauc34f() {
        return pauc34f;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.PAUC34f
     *
     * @param pauc34f the value for 生物群落201809bacteria.PAUC34f
     *
     * @mbg.generated
     */
    public void setPauc34f(String pauc34f) {
        this.pauc34f = pauc34f == null ? null : pauc34f.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Planctomycetes
     *
     * @return the value of 生物群落201809bacteria.Planctomycetes
     *
     * @mbg.generated
     */
    public String getPlanctomycetes() {
        return planctomycetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Planctomycetes
     *
     * @param planctomycetes the value for 生物群落201809bacteria.Planctomycetes
     *
     * @mbg.generated
     */
    public void setPlanctomycetes(String planctomycetes) {
        this.planctomycetes = planctomycetes == null ? null : planctomycetes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Proteobacteria
     *
     * @return the value of 生物群落201809bacteria.Proteobacteria
     *
     * @mbg.generated
     */
    public String getProteobacteria() {
        return proteobacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Proteobacteria
     *
     * @param proteobacteria the value for 生物群落201809bacteria.Proteobacteria
     *
     * @mbg.generated
     */
    public void setProteobacteria(String proteobacteria) {
        this.proteobacteria = proteobacteria == null ? null : proteobacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Rokubacteria
     *
     * @return the value of 生物群落201809bacteria.Rokubacteria
     *
     * @mbg.generated
     */
    public String getRokubacteria() {
        return rokubacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Rokubacteria
     *
     * @param rokubacteria the value for 生物群落201809bacteria.Rokubacteria
     *
     * @mbg.generated
     */
    public void setRokubacteria(String rokubacteria) {
        this.rokubacteria = rokubacteria == null ? null : rokubacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Spirochaetes
     *
     * @return the value of 生物群落201809bacteria.Spirochaetes
     *
     * @mbg.generated
     */
    public String getSpirochaetes() {
        return spirochaetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Spirochaetes
     *
     * @param spirochaetes the value for 生物群落201809bacteria.Spirochaetes
     *
     * @mbg.generated
     */
    public void setSpirochaetes(String spirochaetes) {
        this.spirochaetes = spirochaetes == null ? null : spirochaetes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Synergistetes
     *
     * @return the value of 生物群落201809bacteria.Synergistetes
     *
     * @mbg.generated
     */
    public String getSynergistetes() {
        return synergistetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Synergistetes
     *
     * @param synergistetes the value for 生物群落201809bacteria.Synergistetes
     *
     * @mbg.generated
     */
    public void setSynergistetes(String synergistetes) {
        this.synergistetes = synergistetes == null ? null : synergistetes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.TA06
     *
     * @return the value of 生物群落201809bacteria.TA06
     *
     * @mbg.generated
     */
    public String getTa06() {
        return ta06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.TA06
     *
     * @param ta06 the value for 生物群落201809bacteria.TA06
     *
     * @mbg.generated
     */
    public void setTa06(String ta06) {
        this.ta06 = ta06 == null ? null : ta06.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Tenericutes
     *
     * @return the value of 生物群落201809bacteria.Tenericutes
     *
     * @mbg.generated
     */
    public String getTenericutes() {
        return tenericutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Tenericutes
     *
     * @param tenericutes the value for 生物群落201809bacteria.Tenericutes
     *
     * @mbg.generated
     */
    public void setTenericutes(String tenericutes) {
        this.tenericutes = tenericutes == null ? null : tenericutes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Thermotogae
     *
     * @return the value of 生物群落201809bacteria.Thermotogae
     *
     * @mbg.generated
     */
    public String getThermotogae() {
        return thermotogae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Thermotogae
     *
     * @param thermotogae the value for 生物群落201809bacteria.Thermotogae
     *
     * @mbg.generated
     */
    public void setThermotogae(String thermotogae) {
        this.thermotogae = thermotogae == null ? null : thermotogae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Verrucomicrobia
     *
     * @return the value of 生物群落201809bacteria.Verrucomicrobia
     *
     * @mbg.generated
     */
    public String getVerrucomicrobia() {
        return verrucomicrobia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Verrucomicrobia
     *
     * @param verrucomicrobia the value for 生物群落201809bacteria.Verrucomicrobia
     *
     * @mbg.generated
     */
    public void setVerrucomicrobia(String verrucomicrobia) {
        this.verrucomicrobia = verrucomicrobia == null ? null : verrucomicrobia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.WPS-2
     *
     * @return the value of 生物群落201809bacteria.WPS-2
     *
     * @mbg.generated
     */
    public String getWps2() {
        return wps2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.WPS-2
     *
     * @param wps2 the value for 生物群落201809bacteria.WPS-2
     *
     * @mbg.generated
     */
    public void setWps2(String wps2) {
        this.wps2 = wps2 == null ? null : wps2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.WS1
     *
     * @return the value of 生物群落201809bacteria.WS1
     *
     * @mbg.generated
     */
    public String getWs1() {
        return ws1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.WS1
     *
     * @param ws1 the value for 生物群落201809bacteria.WS1
     *
     * @mbg.generated
     */
    public void setWs1(String ws1) {
        this.ws1 = ws1 == null ? null : ws1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.Zixibacteria
     *
     * @return the value of 生物群落201809bacteria.Zixibacteria
     *
     * @mbg.generated
     */
    public String getZixibacteria() {
        return zixibacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.Zixibacteria
     *
     * @param zixibacteria the value for 生物群落201809bacteria.Zixibacteria
     *
     * @mbg.generated
     */
    public void setZixibacteria(String zixibacteria) {
        this.zixibacteria = zixibacteria == null ? null : zixibacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 生物群落201809bacteria.empty
     *
     * @return the value of 生物群落201809bacteria.empty
     *
     * @mbg.generated
     */
    public String getEmpty() {
        return empty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 生物群落201809bacteria.empty
     *
     * @param empty the value for 生物群落201809bacteria.empty
     *
     * @mbg.generated
     */
    public void setEmpty(String empty) {
        this.empty = empty == null ? null : empty.trim();
    }
}